### ISSUE TITLE
Contours du projet (solutions logicielles)

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#1]
#### Solutions logicielles
Développement réalisé sur Debian Stretch 64

* #### Frontend
  * NodeJS 8.11.2
  * Angular 6.0.6
  * Leaflet 1.3.1
  * Bootstrap 4.1.1

* #### Backend
  * Python 3.5
  * Flask (moteur de l'API)
  * Marshmallow
  * flask-jwt-extended (pour l'authentification)

Biolovision ([wiki de l'API](https://wiki.biolovision.net/index.php/API/v1))

**Comment by lpofredc** [comment]
#### Ressources annexes
La gestion des taxons concernés par le portail s'appuiera sur [TaxHub](https://github.com/PnX-SI/TaxHub) qui lui même s'appuie sur [UsersHub](https://github.com/PnEcrins/UsersHub/)

La procédure d'installation de modules complémentaires s'appuiera sur les fonctionnalités développés dans [GeoNature V2](https://github.com/PnX-SI/GeoNature/blob/geonature2beta/docs/development.rst#d%C3%A9velopper-un-gn_module) (`external_modules`)

**Comment by orovellotti** [comment]
On part donc sur Angular avec un test de Universal pour le SEO 
https://angular.io/guide/universal
