### ISSUE TITLE
[NS] Internationalisation

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#10]
Ne pas mettre de français en dur dans l'interface.
Il faut pouvoir traduire un fichier de langue (I8n) ?
https://www.i18next.com/

**Comment by orovellotti** [comment]
Ce qui est en base n'est pas en mutli lingue

**Comment by patkap** [comment]
Le système est en place. Il faut annoter toutes les balises qui contiennent du texte à traduire avec la directive `i18n`

**Comment by camillemonchicourt** [comment]
OK je vois bien le paramètre dans la conf qui définit la langue de l'instance GN-citizen : https://github.com/PnX-SI/GeoNature-citizen/blob/dev/config/default_config.toml.example#L13

Mais je n'ai pas trouvé les fichiers de langue ?

**Comment by patkap** [comment]
Une fois générés (nous avons suivi le [guide officiel](https://angular.io/guide/i18n#create-a-translation-source-file)), on les retrouve dans `frontend/src/locale/messages.${lang}.xlf`

**Comment by camillemonchicourt** [comment]
OK merci
