### ISSUE TITLE
Quel contenu du pied de page (footer)

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#102]
Le pied de page actuel est sommaire et à améliorer, A minima, il faudrait un lien vers une page statique des mentions légales.

Je fais cette première proposition de contenu.
`[nom local de l'appli] - [description succincte], [années de fonctionnement] - mentions légales - Réalisé avec GeoNature-Citizen`

![Capture d’écran - 2019-05-13 à 17 15 14](https://user-images.githubusercontent.com/22891423/57632819-b5fe3b80-75a2-11e9-833e-47da47c7f036.png)

Personnellement, je préfère un pied de page léger et discret (une seule ligne comme actuellement). Mais à voir si ça reste compatible avec toutes les infos à y rentrer.
Sur petit écran, peut-être ne conserver que le nom de l'appli et le lien vers les mentions légales.

A vous lire.

**Comment by DonovanMaillard** [comment]
Il me semblerait intéressant de procéder comme sur GN atlas à ce niveau et avoir une template footer qui est modifiable par chacun. Ca permet de se plier au mieux aux contraintes de chacun sur les affichages de financeurs, les mentions légales, les liens vers le site de la structure ou autre :)

**Comment by camillemonchicourt** [comment]
Oui c'est ce qu'on souhaitait. 
Des templates HTML surcouchable comme dans GN-atlas. Simple et efficace.

**Comment by DonovanMaillard** [comment]
Tout en gardant par défaut la proposition de Fred, qui va bien à mon sens :)

**Comment by samuelpriou** [comment]
Effectivement conservons par défaut un pied de page léger et discret avec un template HTML qui soit surcouchable. Comme le précise @DonovanMaillard cela permettra de se plier aux contraintes de chacun sur les affichages de financeurs, les mentions légales, etc.

**Comment by orovellotti** [comment]
La tendance est au large footer, pour des questions de référence mais aussi d’ergonomie.

La molette étant énormément utilisée le footer devient la partie la plus importante du site et doit reprendre la navigation et offrir des portes de sorties à l’utilisateur.

**Comment by lpofredc** [comment]
Fixed in PR #190

**Comment by camillemonchicourt** [comment]
Je comprends pas ce qui a été au niveau du footer et de la capacité à le customiser ?

**Comment by samuelpriou** [comment]
Camille, rien n'a été fait au niveau du footer pour le moment.

**Comment by camillemonchicourt** [comment]
OK donc à réouvrir ?

**Comment by lpofredc** [comment]
En effet, je me suis fourvoyé. Le footer a été modifié, maintenant plus esthétique et mieux intégré. Mais il est codé en dur dans le code du front. Je fais une mise à jour pour intégrer le `CSS` et le `HTML` dans le dossier custom du front. ainsi que l'image du background et le logo du site.

![Capture d’écran - 2020-01-08 à 14 27 36](https://user-images.githubusercontent.com/22891423/71981697-2ee19000-3223-11ea-8417-f5c21ff6361e.png)

**Comment by lpofredc** [comment]
html & css customizable (avant compilation) > cf. commit ecfe7bcb034c2ad9a0880b5de84d2e0d9b19d320

**Comment by camillemonchicourt** [comment]
Merci.

**Comment by camillemonchicourt** [comment]
Merci. J'ai fixé 2 mini typos de l'écriture de GeoNature-citizen dans la branche ``dev``.
