### ISSUE TITLE
Esthétique de la page de chargement de l'app

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#104]
L'esthétique de la page de chargement est en décalage avec le reste du site et le chargement de l'image du spinner (icon qui tourne) peut-être longue en cas de connecxion lente , une nouvelle version est proposée, utilisant une animation simple en pur css.

démo ici:
https://jsbin.com/tosexorifo/edit?html,css,output

**Comment by lpofredc** [comment]
intégré dans ce merge #103

**Comment by samuelpriou** [comment]
Merci Fred !
