### ISSUE TITLE
Looking for "Participer au programme"

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#113]
Les boutons "Participer au programme" des blocs programmes de la page d’accueil ont disparu...

![Capture d’écran - 2019-06-17 à 15 13 18](https://user-images.githubusercontent.com/22891423/59607855-687e6c80-9114-11e9-94fc-84f573aee711.png)

**Comment by lpofredc** [comment]
Fix in PR #114

**Comment by samuelpriou** [comment]
Oui nous avons fait cette demande car on estime que le scroll permet d'accéder aux programmes et limites les boutons participer au programme que l'on retrouve pour chaque programme.

**Comment by lpofredc** [comment]
Sur le bloc de bienvenue, oui, je suis d'accord, mais là il s'agissait des boutons de chacun des programmes... Donc impossible d'accéder aux programmes depuis l'accueil.
![Capture d’écran - 2019-06-17 à 15 13 18](https://user-images.githubusercontent.com/22891423/59609015-dcba0f80-9116-11e9-8389-dabf3db98570.png)

Correction:
![Capture d’écran - 2019-06-17 à 15 33 19](https://user-images.githubusercontent.com/22891423/59609019-e04d9680-9116-11e9-8ada-327f9d97de94.png)

**Comment by samuelpriou** [comment]
Ok. il faut que les boutons soient effectivement accessible pour chaque programme !
