### ISSUE TITLE
Proposer une api permettant de charger tous les médias d'une instance

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#116]
Pour l'utilisation d'outils annexe de communication, (galerie) il manque une url d'API permettant de lister tous les médias de tous les programmes d'une instance.

**Comment by samuelpriou** [comment]
Salut Fred,
Patrick a testé une connexion à notre instance Taxhub. A priori cela serait fonctionnel même si je ne peux pas le vérifier. Si tel était le cas, on doit pouvoir récupérer l'ensemble des médias ... ?

**Comment by lpofredc** [comment]
Oui, j'ai testé avec l'utilisation d'une instance distante de TaxHub et cela fonctionne (à améliorer car cela charge les fichier originaux parfois lourds, utiliser les fonctionnalités de TaxHub rappelées par @camillemonchicourt > https://github.com/PnX-SI/TaxHub/issues/108). 

Là il s'agit de récupérer les médias déposés par les observateurs.

**Comment by samuelpriou** [comment]
ok je vois.
Merci !

**Comment by patkap** [comment]
L'export des données des participants pourrait aussi s'appuyer sur cette api.

**Comment by lpofredc** [comment]
Fixé dans la PR #366
