### ISSUE TITLE
Cohérence des listes de programmes entre modal et accueil

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#119]
Les deux listes de programmes (fenêtre **modal**) et blocs de l'accueil ne présentent pas le même contenu.
 * Le modal présente la vignette-logo, le titre et la description courte
 * Les blocs présentent la vignette-logo, le titre et la description longue (sur un espace réduit).

![Capture d’écran - 2019-06-19 à 16 05 16](https://user-images.githubusercontent.com/22891423/59773276-a662c880-92ad-11e9-96df-6b76fdeaf7a8.png)

![Capture d’écran - 2019-06-19 à 16 05 39](https://user-images.githubusercontent.com/22891423/59773285-a95db900-92ad-11e9-8169-d0a85027c46b.png)

Je propose pour ces deux éléments d'utiliser le même contenu que le modal:
 * Vignette logo
 * Titre
 * Description courte
 * Plus le bouton pour les blocs

Et aussi de reprendre la même mise en forme/contenu que le modal pour la description courte.

Un choix reste à faire sur la vignette/logo, dans un cas utilise l'image du programme, dans l'autre son logo (cf. origami)

**Comment by samuelpriou** [comment]
Ok pour retenir la proposition faite par @lpofredc   !

**Comment by lpofredc** [comment]
Premiers tests de modification, semblable à la mise en forme du modal (choisir). Proposition de remplacer le bouton Participer au programme par une trame se superposant sur le programme:

![1_291](https://user-images.githubusercontent.com/22891423/60140420-02e44d00-97b2-11e9-8197-7cffa6e67f16.png)

**Comment by samuelpriou** [comment]
Excellente idée !

**Comment by lpofredc** [comment]
Démo ici. C'est c'est bon pour tout le monde, je ferai un PR.

[http://v2327.phpnet.fr/obs/home](http://v2327.phpnet.fr/obs/home)

**Comment by camillemonchicourt** [comment]
Ouais bien, par contre c'est à mettre au singulier "Participer au programme".

**Comment by lpofredc** [comment]
Je me disais bien qu'il y au moins une personne pour le voir :) Oui, c'est une erreur du fichier de configuration. Ce sera corrigé dans la config par défaut.

**Comment by samuelpriou** [comment]
C'est bien avec cette nouvelle trame ! Ok pour la PR

**Comment by lpofredc** [comment]
Pour la cohérence, fais-t-on la même fonctionnalité sur le modal des programmes, ouvert depuis la barre du haut?

**Comment by lpofredc** [comment]
Fait ici a95a6d2c5ab68729081f5bfd533f074e041d3726
