### ISSUE TITLE
Sights are related to programs (foreign key between t_sights and t_programs)

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#13]
Adding a foreign key field to relate observations to programs

**Comment by camillemonchicourt** [comment]
Yes.
But at the same time I have another question.
Not sure to understand this word "sight". The right shouldnt be "observations" instead of "sights" ?

**Comment by lpofredc** [comment]
That's right, it's an old and bad habit :-\ . wich one would be preferable and the more logical ? `Sightings` or `observations`?

**Comment by lpofredc** [comment]
Done.
