### ISSUE TITLE
Mode mono programme

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#130]
En mode mono programme, quelques correctifs à apporter :
* La position et le style du texte : Scrollet pour en savoir plus
* Le lien Participez au programme ne fait rien
* Le texte d'intro de la plateforme n'est pas visible.

![Capture d’écran - 2019-06-26 à 15 08 06](https://user-images.githubusercontent.com/22891423/60182270-50999d80-9824-11e9-8f21-7c2980f4696f.png)

**Comment by lpofredc** [comment]
Non corrigé à ce jour

**Comment by camillemonchicourt** [comment]
A priori corrigé dans la version 0.3.0.
