### ISSUE TITLE
Cumul des zones couvertes par les programmes lors de la navigation entre programmes

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#134]
Lorsque l'on navigue entre programmes, les zonages de programmes s'accumulent sur la carte. Lors d'un changement de programme, cette zone doit être réinitialisée.

![Capture d’écran - 2019-07-01 à 01 24 32](https://user-images.githubusercontent.com/22891423/60403561-26870900-9b9f-11e9-81f3-4507c207fc84.png)

**Comment by samuelpriou** [comment]
Bien vu !

**Comment by lpofredc** [comment]
Fixed in PR #137
