### ISSUE TITLE
Pas d'affichage de nom_commun si nom_vern est vide

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#139]
Cas de l'utilisation d'espèces peu communes ou de taxons supérieurs (ex: ordre Chiroptera).

**Comment by lpofredc** [comment]
Fixed in PR #140 

![Uploading Capture d’écran - 2019-07-03 à 00.40.23.png…]()

**Comment by lpofredc** [comment]
![Capture d’écran - 2019-07-03 à 00 40 23](https://user-images.githubusercontent.com/22891423/60551363-6bd84180-9d2b-11e9-931a-c004dfc00fde.png)

**Comment by xavyeah39** [comment]
Je me permet de réouvrir car j'ai de nouveau ce soucis après MàJ en 1.0.0 puis 1.1.0.
Pour le taxon Chiroptera nous avions défini un nom français via Taxhub pour que ce dernier s'affiche bien.
Aujourd'hui ce n'est plus le cas. En revanche c'est OK si j'ajoute un `nom_vern` sur le taxon Chiroptera (cd_nom = 186233) dans la table `taxonomie.taxref`

![image](https://github.com/PnX-SI/GeoNature-citizen/assets/16793813/374b09b4-89df-44af-9167-b73c6f7aaeac)

En complément, ne serait-il pas judicieux que le nom scientifique s'afiche si le taxon n'a pas de nom vernaculaire ?

**Comment by camillemonchicourt** [comment]
Comme mentionné par ailleurs, on va supprimer `bib_noms` de TaxHub, donc il n'est pas souhaitable que GN-citizen s'appuie sur le contenu de cette table, mais uniquement sur Taxref.
Si besoin de compléter ou surcoucher des noms français, il faudra plutôt envisager d'utiliser un attribut TaxHub dédié à cela.
