### ISSUE TITLE
Azuré un jour, azuré toujours

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#141]
Aujourd'hui, la photo d'Azuré est *hardcodée* dans le frontend. 

Je propose de rendre la photo d'azuré (image par défaut lorsque pas d'autre image pour les observations) personnalisable. Deux scénarios possibles :

1. Personnalisation globale pour toute l'appli > dans le fichier de configuration du frontend ou avec une image custom.
2. Personnalisation au programme (le plus souple et intéressant de mon avis) > dans la table de programme.

Faites vos jeux :)

**Comment by camillemonchicourt** [comment]
Cette photo n'a pas de sens et porte en effet à confusion plus qu'autre chose.

Pour moi quand y a pas d'image je mettrai pas d'image plutôt que de mettre une image qui n'a pas de sens.

Mais le moins insensé serait de mettre l'image du programme.

**Comment by patkap** [comment]
... ou de piocher aléatoirement dans les ressources du cd_nom ou cd_ref ou cd_sup de TaxHub ?

**Comment by lpofredc** [comment]
Image générique par défaut ajoutée ici 7185fd58bec8bf53e3edbc7f581769f3e0fe8ec0

![](https://raw.githubusercontent.com/PnX-SI/GeoNature-citizen/7185fd58bec8bf53e3edbc7f581769f3e0fe8ec0/frontend/src/assets/default_image.png)
