### ISSUE TITLE
Avatar utilisateur

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#145]
Dans l'immédiat, il parait nécessaire de trouver un avatar plus générique pour l'utilisateur (image de nature, d'animal?). Pensons à *Nathalie* qui n'a peut-être pas envie de se voir attribuer un avatar barbu.

![Capture d’écran - 2019-07-05 à 00 02 31](https://user-images.githubusercontent.com/22891423/60688881-5a707000-9eb8-11e9-9fc8-efed61347260.png)

**Comment by samuelpriou** [comment]
Dans l'idéal il faudrait que l'utilisateur puisse uploader la photo de son choix. En attendant cette évolution on peut effectivement faire le choix d'une image de nature.

**Comment by jbdesbas** [comment]
Ou alors laisser la gestion des avatars à [gravatar](http://fr.gravatar.com/) ?

**Comment by camillemonchicourt** [comment]
En option si vous voulez, mais attention à ne pas imposer de dépendance de l'outil à des outils tiers. 

On peut aussi se demander, a t-on besoin d'avatar dans GeoNature-citizen ? Non selon moi.

**Comment by lpofredc** [comment]
Personnellement, je serai pour que l'avatar par défaut soit une image neutre (ni homme/ni femme).

**Comment by camillemonchicourt** [comment]
Oui !

**Comment by samuelpriou** [comment]
Quelque chose comme ça [https://www.jing.fm/iclip/u2q8t4u2t4o0w7u2_simple-avatar-icon-person-icon-png-free-transparent/](url) ?

**Comment by lpofredc** [comment]
Je propose de mettre ça par défaut (si, rien n'est spécifié dans la configuration) mais avec la possibilité de le personnaliser via la configuration.

**Comment by lpofredc** [comment]
Fixed in PR #190
