### ISSUE TITLE
[NS] Visualiser et modifier ses données - tableau de bord{

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#148]
Il faudrait que chaque utilisateur ayant un compte puisse consulter et avoir un historique des données qu'il a saisie dans GeoNature Citizen.
Cette synthèse des données utilisateur aurait sa place dans le tableau de bord.

**Comment by lpofredc** [comment]
Il semble y a voir plusieurs pb sur l'API qui génère les données utilisateurs, pour récupérer les données TAXREF des observations:

```

File "/home/fcloitre/Dev/gn_projects/gncitizen/backend/gncitizen/core/observations/routes.py", line 756, in get_observations_by_user_id

ProgramsModel.query.one().taxonomy_list

File "/home/fcloitre/.pyenv/versions/3.7.4/envs/gnc/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3295, in one

"Multiple rows were found for one()"
```
Par ailleurs, cette requête est surprenante ici car les données peuvent provenir de plusieurs programmes. Ne serait-il pas plus intéressant de créer une fonction générique de serialisation d'observations utilisable dans les différentes API (toutes les observations, obs d'un programme, etc.)

**Comment by lpofredc** [comment]
Il faut ajouter à l'export des observations pour l'utilisateur leurs coordonnées géographiques (X/Y).

**Comment by samuelpriou** [comment]
- Ajouter une carte sur le tableau de bord utilisateur pour afficher ses observations.
- Ajouter un paramètre applicatif permettant de personnaliser le nombre d'observations à afficher sur la carte (par défaut 50).

**Comment by camillemonchicourt** [comment]
Fait dans la version 0.99 il me semble ?
