### ISSUE TITLE
Bouton de recentrage : à remplacer

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#162]
Sur la saisie, l'icône ![image](https://user-images.githubusercontent.com/9743288/64541231-d0aeaa00-d321-11e9-8b21-5800240d71e5.png) du bouton de recentrage sur ma position ressemble à une icône de marqueur portant confusion avec l'outil de localisation d'une observation. 
Utiliser plutôt une icône de géolocalisation classique et moins confuse du type 
![image](https://user-images.githubusercontent.com/9743288/64541313-f3d95980-d321-11e9-8c85-672816d3c501.png)

**Comment by lpofredc** [comment]
GeoNature-citizen s'appuie sur la librairie d'icone Font-Awesome pour laquelle cette icone n'est pas disponible. Proposition d'utiliser une icone de boussole à la place, tout aussi explicite.

![Capture d’écran du 2019-09-09 22-02-51](https://user-images.githubusercontent.com/22891423/64562599-a541b480-d34d-11e9-9dc3-b6e1b4d1fd1e.png)

**Comment by camillemonchicourt** [comment]
Oui

**Comment by camillemonchicourt** [comment]
Ou parmis les différentes déclinaisons de "location" bien adaptés à la fonctionnalité
https://fontawesome.com/icons?d=gallery&q=Locate

**Comment by lpofredc** [comment]
Fixed in commit 5a46b7c5ebdd3b5a28c9fb4b66d13014e56dd91e (dev branch actually)
 
![Capture d’écran du 2019-09-10 01-08-04](https://user-images.githubusercontent.com/22891423/64572461-b7c8e780-d367-11e9-82b8-0ff591e71a3c.png)

**Comment by camillemonchicourt** [comment]
OK c'est mieux.
Même si, pour être pointilleux, cette icône correspond habituellement à la fonctionnalité "Réorienter la carte" et que pour le recentrage c'est plutôt "location" qui correspond bien : https://fontawesome.com/icons?d=gallery&q=Location
L'idéale est en offre pro, du coup la seule accessible semble être "location-arrow".

**Comment by lpofredc** [comment]
Nous sommes en version 4.7 de font-awesome, on peut donc partir sur celle-ci
https://fontawesome.com/v4.7.0/icon/location-arrow
