### ISSUE TITLE
Ajouter des statistiques générales à la plateforme

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#165]
Créer une route générant des statistiques générales de la plateforme (nombre d'observateurs enregistrés, nombre de contributions, nombre de programmes, nombre d'espèces, dernières contributions ?), à l'image de ce qui est fait sur GeoNature ou GeoNature-atlas.

Prévoir un affichage modulable et optionnel côté frontend.

![Capture d’écran - 2019-09-10 à 14 14 22](https://user-images.githubusercontent.com/22891423/64612962-4fb0ea80-d3d5-11e9-97c5-a6e598d4474d.png)

**Comment by lpofredc** [comment]
La console du navigateur soulève l'erreur suivante.
```
ERROR TypeError: "_co.stats is undefined"
    View_HomeComponent_0 HomeComponent.ngfactory.js:240
```
Voici le résultat:
![Screen Shot 2019-12-03 at 12 30 16](https://user-images.githubusercontent.com/22891423/70047629-b30f7a80-15c8-11ea-9e2f-c03bd748ddef.png)

**Comment by camillemonchicourt** [comment]
Il faut aussi prévoir un paramètre pour masquer ce bloc de statistiques pour ceux qui ne souhaiteraient pas l'utiliser.

**Comment by lpofredc** [comment]
Ces statistiques ne doivent être calculées que sur les programmes actifs.
