### ISSUE TITLE
Créer un script d'installation

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#167]
Créer un script d'installation d'une instance GeoNature-citizen adaptée à debian (9+) et ubuntu (18.04) pour faciliter les déploiements de GeoNature-citizen.

**Comment by lpofredc** [comment]
Une conteneurisation Docker est prévue pour faciliter le déploiement.

**Comment by camillemonchicourt** [comment]
OK, mais cela imposerait Docker ? 
Ou une installation classique sur un serveur Debian ou Ubuntu resterait maintenue ?

**Comment by lpofredc** [comment]
En ce qui me concerne, je vais privilégier Docker car répond à mon besoin (hébergement de plusieurs instances sur un serveur unique et besoin de déploiements rapides). 

Cependant, le travail réalisé pour la conteneurisation permettra d'élaborer assez facilement des script d'installation en "dur" sur Debian ou Ubuntu car très similaires. Tout au moins dans les grandes lignes (installation des paquet et librairies, patch des librairies du front, mise en ligne avec un serveur web avec proxy reverse de l'API).

**Comment by camillemonchicourt** [comment]
Je pense que proposer un déploiement Docker est un plus. 
Mais pas sur que ne proposer que cela soit une bonne chose.

**Comment by vtellier** [comment]
La containerisation m'intéresse grandement, peut-on espérer la voir prochainement en master ?

**Comment by camillemonchicourt** [comment]
Je ne sais pas si quelqu'un a fait une containérisation qui est fonctionnelle. 
Ce qui est prévu actuellement est de faire un script qui automatise l'installation classique.

**Comment by samuelpriou** [comment]
Bonjour Vincent,
Un script de déploiement de GeoNature Citizen et de ses dépendances est en cours. Cette documentation pourrait être disponible en fin de semaine prochaine .
Merci pour ces premiers retours !

**Comment by lpofredc** [comment]
A ce jour, pas de conteneurisation fonctionnelle. La conteneurisation pourra être envisagée le travail d'automatisation avancé.

**Comment by Splendens** [comment]
Bonjour. Il y a-t-il des nouvelles de ce script d'installation auto de GN-citizen ?

**Comment by samuelpriou** [comment]
@Splendens, un commit avec le script en cours de validation a été posté ici : [https://github.com/PnX-SI/GeoNature-citizen/commit/823d29bdfd1fd5ed6a74d10fb8413f9e62a18578#commitcomment-42669107](url).
N'hésitez pas à nous faire des retours sur ce script.

Merci

**Comment by camillemonchicourt** [comment]
Pas de script en vue pour le moment.
Mais en effet une révision/complément de la documentation à relire : https://github.com/PnX-SI/GeoNature-citizen/commit/823d29bdfd1fd5ed6a74d10fb8413f9e62a18578

**Comment by Splendens** [comment]
Super, merci pour le lien ! 

Du coup, après un premier test (sur debian 10),  quelques remarques sur le scripts d'installation :  

Ligne 326 / 327, il manque les `;` à la fin des instructions : 
```
find src/conf/ -iname "*template" -exec bash -c 'cp $0 ${0/.template/}' {} \;
find src/custom/ -iname "*template" -exec bash -c 'cp $0 ${0/.template/}' {} \;
```

Pour arriver à lancer le program _citizen_, j'ai du installer gunicorn3
`sudo apt install gunicorn3 -y`


Juste avant l'exemple de fichier de configuration Apache, on pourrait rajouter une ligne pour créer le fichier de config : 
`sudo nano /etc/apache2/sites-available/citizen.conf
`

-----------
Sinon, je suis bloquée sur la config Apache pour ce soir... Est-ce que que quelqu'un aurait un autre exemple de config apache pour citizen à partager ? En particulier une config en sous-domaine ? 

Merci d'avance 👍

**Comment by camillemonchicourt** [comment]
OK merci car on a besoin de retours sur cette révision de la doc.
Elle est donc mieux que celle actuelle qu'elle vise à remplacer ?
Et avec les 2 détails que tu évoques, elle fonctionne aussi sous Debian 10 ?
Si oui, on va pouvoir ajouter Debian 10 dans les versions supportées dans la doc en ajoutant les 2 éléments que tu précises.

Pour la conf Apache, je ne sais pas, mais quelqu'un doit avoir ça ?

**Comment by DonovanMaillard** [comment]
J'imagine qu'on doit pouvoir repartir de ce qui avait été documenté pour GeoNature [ici](http://docs.geonature.fr/conf-apache.html)

**Comment by samuelpriou** [comment]
Bonjour à tous,

Merci Marie pour ton retour.
Pour la conf apache nous avons ça :
[geocitizen-le-ssl.zip](https://github.com/PnX-SI/GeoNature-citizen/files/5281062/geocitizen-le-ssl.zip).

**Comment by Splendens** [comment]
Merci pour le partage !

Pour faire une première réponse, je peux lancer le program _citizen_, et je ne trouve pas d'erreur dans les logs. 

Par contre, aucune idée de si ça fonctionne ou pas car je suis bloquée avec la config d'apache : j'ai suivi la doc dans l'optique d'accéder à l'instance de citizen à l'adresse `http://MON.IP/citizen` mais pour le moment j'ai seulement le droit à des erreurs "Not Found" et rien dans les logs

**Comment by Splendens** [comment]
Bon, je laisse tomber l'affaire pour accéder au site sur une url du style `http://xx.xxx.xx.xx/citizen`, la configuration d'Apache me dépasse !

Grâce à la conf de @samuelpriou (encore merci ! ), j'accède bien à l'appli sur un sous-domaine et en https (cf https://citizen.marie-filipe.fr/)

Du coup, en dehors des coquilles que j'ai dû corriger pour parvenir à finir l'installation sur Debian 10 (et en dehors de la partie Apache...), la doc est claire. @camillemonchicourt : il n'y a pas photo, cette doc est bien mieux que l'actuelle !

Pour rappel, j'ai également dû modifier la ligne 95 par `sudo pip3 install -r requirements.txt` (https://github.com/PnX-SI/GeoNature-citizen/issues/234).

------------------
Bon, c'est quand même pas parfait de mon côté : maintenant j'ai plein d'erreurs et en particulier les données non  récupérées et des ERR_CONNECTION_REFUSED dans tous les sens...

Il n'y aurait pas une doc "paramétrage" sur le feu à relire tant que j'y suis ? ;-)

**Comment by camillemonchicourt** [comment]
Merci des retours. On va pouvoir compléter/corriger la doc avec ces éléments.
Il y a d'autres éléments dans la docs, dont certains dans ``dev`` utiles en prod... : https://github.com/PnX-SI/GeoNature-citizen/tree/master/docs

A revoir aussi, n'hésite pas à nous dire.

**Comment by camillemonchicourt** [comment]
@lpofredc a faire une relecture et des compléments de cette révision de la doc ici : https://github.com/PnX-SI/GeoNature-citizen/pull/235/files
@Splendens cela inclut tes commentaires et répond à tes soucis de conf Apache ?

Reste selon moi à réorganiser les fichiers du dossier /docs/ (https://github.com/PnX-SI/GeoNature-citizen/tree/master/docs) et ne plus avoir des infos utiles en prod dans le dossier /docs/dev/

**Comment by Splendens** [comment]
Je viens de réessayer de faire une installation de 0 (enfin, j'ai quand même GN et Taxhub) sur Debian 10 en suivant la doc modifiée.

Lignes 399 / 400, les commandes :  
```
find src/conf/ -iname "*template" -exec bash -c 'cp $0 ${0/.template/}' {} \
find src/custom/ -iname "*template" -exec bash -c 'cp $0 ${0/.template/}' {} \
```
Me renvoient l'erreur : `find: paramètre manquant pour « -exec »` (solution : des `;` à la fin des commandes)

En suivant la doc, j'ai l'impression que le venv doit être activé en permanence. Est-ce le cas ? Sinon, ce serait pas mal de mettre des `deactivate`.

Dans l'exemple de config d'Apache, attention, il y a une erreur dans le DocumentRoot  et Directory :   `/home/geonatadmin/GeoNature-citizen/frontend/dist/browser/`  le dossier n'est plus nommé `GeoNature-citizen` dans le reste de la doc, mais `gncitizen`

------------------

> @Splendens cela inclut tes commentaires et répond à tes soucis de conf Apache ?

Au début de la doc, dans le **default_config.toml** il est écrit qu'on défini l'url d'acces au site sous cette forme :  `http://ADRESSE_IP/citizen`, mais on ne retrouve le `/citizen` nul part dans la conf apache ?  

En suivant cette doc j'ai accès à un site GN-citizen à l'adresse http://MON_IP/citizen mais j'arrive sur une page 'not found 404'. Et l'outil ne fonctionne pas : pas de programme de test, les images ne s'affichent pas, et j'ai la popup d'erreur "données non récupérées sur le serveur". Cela vient des fichiers de configuration j'imagine ?

**Comment by lpofredc** [comment]
Je viens de mettre à jour la doc. en testant une install sous debian 10 (avec un install fraiche de geonature).

Plusieurs choses (ajoutées dans la PR #235) pour fixer le lancement de l'API
- Installer gunicorn dans le venv (ajouté dans le requirements.txt dans la PR #235)
- Modifier `gunicorn3` par `gunicorn` dans le fichier  `backend/start_gunicorn.sh`

Pour le front, si on veut servir le site dans un chemin spécifique (ex: http://url.com/citizen), alors il faut ajouter `--base-href=/citizen/` à la commande de compilation du front. et ajouter un Alias à la config Apache (cf doc revue). c'est bien plus simple avec un sous-domaine...

**Comment by lpofredc** [comment]
Doc d'installation revue ici: https://geonature-citizen.readthedocs.io/fr/latest/

Merci à @camillemonchicourt, @ksamuel, @samuelpriou  et @Splendens

**Comment by Adrien-Pajot** [comment]
Fermable ?

**Comment by lpofredc** [comment]
Avec la sortie de la V1 et le script d'installation éprouvé 👍🏻

**Comment by camillemonchicourt** [comment]
Script corrigé et amélioré dans la version 1.0.0.
