### ISSUE TITLE
Faire sortir les fichiers personnalisables du dépot (customisation)

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#168]
Le logo et l'image du bandeau d’accueil, personnalisés, sont susceptibles d'être écrasés par une mise à jour. Il faut les faire sortir du dépot (les inscrire dans le fichier `.gitignore`) et en faire des fichiers exemples (`logo.png.sample` par exemple) installés lors du déploiement d'une instance (`cp  logo.png.sample logo.png`)

**Comment by lpofredc** [comment]
Logo & background sont sortis du dépot, servis par l'API. A terme, prévoir des url d'API spécifiques et une personnalisation d'après l'interface d'admin (images & textes de présentation).

**Comment by lpofredc** [comment]
cf. commits 989907c51c7a71b7ae3ce9429457e4216f6c6a0b & ea1fb70ec56976f8b19bcc666fd05a62c017bdca

**Comment by camillemonchicourt** [comment]
Du coup on doit les mettre où et comment ?

**Comment by lpofredc** [comment]
Pour le moment, il faut mettre dans le dossier media le fichier `logo.png` et `background.jpg` dans le dossier media créé pour recevoir les medias chargés dans la plateforme (comme c'est déjà le cas pour les images de badges). L'installation des fichiers génériques dans ce dossier pourra être faite par le script d'installation. A terme, j'imagine plutôt une url d'API listant les principales config amenées à être modifiées par un animateur de la plateforme lien vers le logo, lien vers l'image de background et textes introductifs avec un formulaire d'administration de ces données (chargement des images et modification du texte).

**Comment by camillemonchicourt** [comment]
OK
