### ISSUE TITLE
Configuration apache

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature-citizen#169]
Salut,
J’essaie de configurer Apache mais je galère un peu. Après un peu de bidouillage, j'ai sortie la config ci-dessous qui permet de servir directement les statics existants, et de rediriger le reste sur le `index.html`. Le souci c'est que au refresh d'une page, j'ai une erreur 404, mais qui vient bien de citizen, pas de apache (qui indiquerait un problème dans les _rewrites_). Il me semble donc que le souci provient de l'appli, mais je ne comprend pas pourquoi ??

Merci d'avance,

    # Configuration Citizen
    Alias /citizen /your-local-path/GeoNature-citizen/frontend/dist/browser

    Listen 5003
    <VirtualHost *:5003>
	    DocumentRoot /your-local-path/GeoNature-citizen/frontend/dist/browser
	    <Directory /your-local-path/GeoNature-citizen/frontend/dist/browser>
		    Require all granted
		    RewriteEngine On

		    RewriteBase /
		    RewriteRule ^index\.html$ - [L]
		    RewriteCond %{REQUEST_FILENAME} -s [OR]
		    RewriteCond %{REQUEST_FILENAME} -l [OR]
		    RewriteCond %{REQUEST_FILENAME} -d
		    RewriteRule ^ - [L]		

		    RewriteRule !\.(jpg|css|js|gif|png)$ /index.html [L]
		    RewriteRule ^.*?(assets)\/([^\/]*)$ /$1/$2 [L]
		    RewriteRule ^.*?([^\/]*)$ /$1 [L]
	    </Directory>
	    <Location /api>
		    ProxyPass  http://127.0.0.1:5002 retry=0
		    ProxyPassReverse  http://127.0.0.1:5002
	    </Location>
    </virtualHost>

![image](https://user-images.githubusercontent.com/6163107/67296958-7f313780-f4e9-11e9-8ee1-a9abb273d67d.png)

**Comment by lpofredc** [comment]
en effet, la config est un peu particulière, notamment avec l'interface d'administration backoffice et la doc à reprendre

Voici une config apache fonctionnelle :
```
# Configuration GeoNature-citizen
Alias /obs /home/gnc/gncitizen/frontend/dist/browser

<Directory /home/gnc/gncitizen/frontend/dist/browser>
  Require all granted
  AllowOverride All

  <IfModule mod_rewrite.c>
      Options -MultiViews

      RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteRule ".*" "index.html" [QSA,L]
  </IfModule>

</Directory>
<Location /gnc/api>
  ProxyPass http://127.0.0.1:5002/api retry=0
  ProxyPassReverse  http://127.0.0.1:5002/api
</Location>

<Location /gnc/api/admin>
  ProxyPass http://127.0.0.1:5002/gnc/api/admin retry=0
  ProxyPassReverse  http://127.0.0.1:5002/gnc/api/admin
</Location>
```

**Comment by camillemonchicourt** [comment]
Oui ça serait excellent de mettre la doc au propre et à jour.
@jbdesbas n'hésite pas à corriger/compléter si tu vois des choses.

Merci d'avance.

**Comment by jbdesbas** [comment]
J'ai toujours le même souci avec la config de @lpofredc , 2 problèmes en fait : 
- lorsque je refresh une page (par exemple _obs/programs/2/observations_) firefox tente de charger les fichiers *.js en relatif (ex:obs/programs/2/scripts.js), et avec le rewrite, c'est le contenu de index.html qui est renvoyé. (c'est ce que la config donnée dans les _RewriteRule_ dans le premier post permettaient de contourner)
- si je modifie manuellement le dist/index.html pour mettre des liens absolus vers les fichiers *.js, je retombe sur une erreur 404 au niveau du frontend.

Peut-être un souci au moment du build du frontend ? Je fais 
`nvm use --lts`
`npm rund build`

**Comment by lpofredc** [comment]
Oui, je vois, il s'agit d'un paramètre à ajouter au moment du build pour paramétrer la valeur "href" du front (la valeur  `/citizen` indiquée dans `Alias`. Essaye la commande suivante.
```
npm run build -- --prod --base-href="/citizen/"
```

**Comment by jbdesbas** [comment]
Parfait c'était bien ça ! Merci ( avec `npm run build -- --prod --base-href="/obs/" ` pour être cohérent avec la config apache au dessus)
Je m'occupe d'indiquer ça dans la doc
Merci encore !

**Comment by lpofredc** [comment]
Super. Attention, pour que le backoffice d'admin soit accessible, il faut que le Location de l'API ne redirige pas sur l'alias citizen. Dans mon exemple, le front est accessible sur "/obs", l'api sur "/gnc".

**Comment by jbdesbas** [comment]
Du coup il faut plutôt remplacer ton dernier bloc par ça non ?  (enlevé _/gnc_ dans le ProxyPass )  C'est ce qui fonctionne pour moi

    <Location /gnc/api/admin>
      ProxyPass http://127.0.0.1:5002/api/admin retry=0
      ProxyPassReverse  http://127.0.0.1:5002/api/admin
    </Location>

**Comment by camillemonchicourt** [comment]
Oui ça serait excellent de mettre la doc au propre et à jour.
@jbdesbas n'hésite pas à corriger/compléter si tu vois des choses.

Merci d'avance.
