### ISSUE TITLE
Message d'incitation à l'inscription

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#177]
Ajouter à la fenêtre de d'authentification, affichée lors d'une nouvelle saisie, un message personnalisable expliquant l'intérêt de créer un compte.

![Screen Shot 2019-11-04 at 13 44 54](https://user-images.githubusercontent.com/22891423/68121986-991b4300-ff09-11e9-9f09-12341ca5708a.png)

**Comment by samuelpriou** [comment]
Effectivement cela serait à envisager de sorte à expliquer ce que permet la création d'un compte.

**Comment by lpofredc** [comment]
A mettre en option et à définir dans le fichier de configuration du front.

**Comment by camillemonchicourt** [comment]
Fait : https://github.com/PnX-SI/GeoNature-citizen/commit/098e066684d64f4f5b7fe1da71b5e6433d694e12
