### ISSUE TITLE
Approche "Site"

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#179]
Un développement, porté par la LPO Auvergne-Rhône-Alpes et sa délégation Territoriale Isère, a consisté à développer l'approche "Site" de GeoNature-Citizen (https://github.com/jolleon/GeoNature-citizen). Voici le site officiel du projet : https://www.a-vos-mares.org/

Les développements de ce projet ont été réalisés sur un `fork` de GeoNature-citizen (version de l'hiver dernier) avec de nombreux nouveaux développements sur le dépot principal du projet.

La fusion de ce projet nécessite un important travail de fond. Montées en versions des librairies, reprise des modifications effectuées, mutualisation des composants du frontend. 

Cet outil apporte notamment la possibilité de générer automatiquement un formulaire de collecte de données détaillées à partir de configurations json (a terme stockés en bdd donc personnalisables par types de sites par exemple). Ces données sont alors stockées en bdd dans un champ `jsonb`.

**Comment by camillemonchicourt** [comment]
Voir - https://github.com/PnX-SI/GeoNature-citizen/issues/34

**Comment by orovellotti** [comment]
Super intéressant, il y a une démo quelque part ?

Il est question d’intégrer ces développements dans la branche principale dans un avenir proche ?

**Comment by camillemonchicourt** [comment]
Oui la démo est ci-dessus.
Et ce message est un appel à contribution pour mettre ça au propre et ainsi l'intégrer dans la branche Master. 😀

**Comment by camillemonchicourt** [comment]
Programmes de type SITES intégrés dans la 0.99.0.
