### ISSUE TITLE
Correction des bugs d'affichage et amélioration du rendu pour les mobiles.

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#184]

**Comment by lpofredc** [comment]
Sur grand écran, les programmes listés dans la page d'accueil sont  petits... et petits
![Capture d’écran - 2020-01-08 à 11 58 45](https://user-images.githubusercontent.com/22891423/71973470-562e6200-320f-11ea-8f15-db2e05df14af.png)


Sur "moyen" écran, dans un programme, l'image de présentation de programme est recouverte par la topbar,  ça fonctionne sur petit écran.
![Capture d’écran - 2020-01-08 à 12 03 51](https://user-images.githubusercontent.com/22891423/71973311-f20b9e00-320e-11ea-84ed-a509bed658ce.png)

![Capture d’écran - 2020-01-08 à 12 05 40](https://user-images.githubusercontent.com/22891423/71973413-3bf48400-320f-11ea-8fb3-fd3e69f2cf4b.png)

**Comment by samuelpriou** [comment]
> Sur grand écran, les programmes listés dans la page d'accueil sont petits... et petits
> ![Capture d’écran - 2020-01-08 à 11 58 45](https://user-images.githubusercontent.com/22891423/71973470-562e6200-320f-11ea-8f15-db2e05df14af.png)

 Pas de problème sur un grand écran, il semble que cela ai été corrigé. En tout cas cela fonctionne sur la démo : http://51.83.46.49/citizen/home
![citizen_programmes](https://user-images.githubusercontent.com/9743288/72157725-e956cb80-33b8-11ea-8f08-4509009faae7.jpg)
