### ISSUE TITLE
Installation / Ne pas patcher dépendances

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-citizen#186]
Pour sortir une première version propre, il est nécessaire de ne plus avoir à patcher certaines dépendances comme actuellement : https://github.com/PnX-SI/GeoNature-citizen/blob/master/docs/devs/init_launch_frontend.rst

**Comment by lpofredc** [comment]
Fixé dans https://github.com/HamoudaAmine/GeoNature-citizen/commit/73cf4a3190c937b90044fb797dcf2376cc2e9d8e & https://github.com/HamoudaAmine/GeoNature-citizen/commit/970c8ac72fe4e647dcd1069f07ec2a46025add79

**Comment by camillemonchicourt** [comment]
OK mais pas modifié dans la doc par contre.

**Comment by lpofredc** [comment]
Fixed in PR #190  documentation à mettre à jour

**Comment by lpofredc** [comment]
Fixé https://github.com/HamoudaAmine/GeoNature-citizen/commit/73cf4a3190c937b90044fb797dcf2376cc2e9d8e

**Comment by camillemonchicourt** [comment]
Pas mis à jour dans la doc, non ? 
https://github.com/PnX-SI/GeoNature-citizen/blob/dev/docs/devs/init_launch_frontend.rst

**Comment by lpofredc** [comment]
Non, pas encore. Je propose de continuer ce sujet dans l'issue dédié: https://github.com/PnX-SI/GeoNature-citizen/issues/166
