### ISSUE TITLE
Personnalisation des titres de page et meta

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#205]
Pour une meilleure visibilité et un meilleur référencement, notamment en mode rendu server (ServerSideRendering):
* Personnalisation des meta de la plateforme, depuis le fichier de configuration.
* Personnalisation des balises `title` & `meta` des programmes avec respectivement:
  * `title` : Nom de la plateforme (depuis le fichier de config `appName`) + Intitulé du programme
  * `meta.description`: Description courte du programme

**Comment by lpofredc** [comment]
Ajouté dans le commit https://github.com/PnX-SI/GeoNature-citizen/commit/3fd65daeee2a3c56696f6ce1b89c3f57b70d003f

**Comment by camillemonchicourt** [comment]
Fait dans la 0.99.0
