### ISSUE TITLE
Pouvoir personnaliser les libelles programmes

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#207]
Les libellés "Programmes" & "Programme" doivent être personnalisables ex: Enquêtes, Missions, etc.

**Comment by camillemonchicourt** [comment]
C'est désormais le cas : https://github.com/PnX-SI/GeoNature-citizen/blob/1.0.0/frontend/src/conf/app.config.ts.template#L37-L47
