### ISSUE TITLE
Uploader plusieurs photos

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#208]
A l'usage il serait intéressant de pouvoir laisser la possibilité à l'observateur de charger 3 photos.
Nous souhaiterions notamment faire saisir les bouquetins marqués d'où l'idée de pouvoir ajouter plus d'une photo.

**Comment by camillemonchicourt** [comment]
OK idéalement sans limiter à 3 photos mais avoir une table de correspondance pour en ajouter plusieurs sans limite technique.

**Comment by samuelpriou** [comment]
@camillemonchicourt Oui tout à fait !

**Comment by lpofredc** [comment]
Oui, je rejoins @camillemonchicourt.

c'est déjà fonctionnel cote backend, reste a gérer côté frontend.

**Comment by lpofredc** [comment]
Déjà réalisé dans les derniers devs en cours (PR à venir, aujourd'hui ici: https://github.com/jolleon/GeoNature-citizen/tree/pnm)
