### ISSUE TITLE
Permettre un programme site et un programme obs

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#209]
Il serait bien de pouvoir sur une même instance GeoNature citizen de pouvoir mélanger un programme espèce et un programme site.

**Comment by camillemonchicourt** [comment]
Oui c'est ce qui a été ciblé initialement : https://github.com/PnX-SI/GeoNature-citizen/issues/34

Et c'est toujours l'objectif, mais pour l'instant les développements ont une base commune mais ont divergé et n'ont pas été fusionné. C'est le sujet évoqué ici : https://github.com/PnX-SI/GeoNature-citizen/issues/179

Mais quand les 2 développements seront fusionnés, alors le type de programme sera défini au niveau du programme, ainsi que ses champs additionnels stockés en ``jsonb``.

**Comment by lpofredc** [comment]
Modules sites et observations maintenant disponibles dans une instance unique de GeoNature-citizen
