### ISSUE TITLE
InvalidForeignKey sur taxonomie.bib_noms (cd_ref)

### ISSUE THREAD

**Issue by vtellier** [PnX-SI/GeoNature-citizen#214]
Lors de l'initialisation de la base de données, la clef étrangère suivante pose problème. Je contourne le problème en commentant la déclaration de la foreign key.

Une clef étrangère sur un champ qui n'est pas la clef primaire a-t-elle lieu d'être ?

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "bib_noms"

[SQL: 
CREATE TABLE taxonomie.t_medias (
	id_media SERIAL NOT NULL, 
	cd_ref INTEGER NOT NULL, 
	titre VARCHAR, 
	url VARCHAR, 
	chemin VARCHAR, 
	auteur VARCHAR, 
	desc_media TEXT, 
	is_public BOOLEAN, 
	supprime BOOLEAN, 
	id_type INTEGER, 
	source TEXT, 
	licence TEXT, 
	PRIMARY KEY (id_media), 
	FOREIGN KEY(cd_ref) REFERENCES taxonomie.bib_noms (cd_ref)
)

]
(Background on this error at: http://sqlalche.me/e/f405)

```

Peut-être aussi est-ce ma configuration qui est en cause:
```
postgres=# SELECT version();
                                                                version                                                                 
----------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
(1 row)

postgres=# \q
(venv) vtellier@ubuntu:~/github/vtellier/GeoNature-citizen/backend$ python --version
Python 3.6.9
```

Le commit: c17bc49c7960a899261b0a04e9ae91df8368f117

**Comment by camillemonchicourt** [comment]
Je me demande si c'est au niveau de TaxHub ou SQLAlchemy de GN-citizen ?
@lpofredc, à cause du ``cd_ref`` ici : https://github.com/PnX-SI/GeoNature-citizen/blob/master/backend/gncitizen/core/taxonomy/models.py#L72 ? A remplacer par ``cd_nom`` ?

**Comment by vtellier** [comment]
Merci pour les précisions, j'avai effectivement installé TaxHub au préalable, mais dans une autre base de données, citizen n'avait donc pas accès au schéma.

**Comment by camillemonchicourt** [comment]
Ah OK, bien vu. Oui du coup c'est aussi à clarifier dans la documentation en effet.
