### ISSUE TITLE
Positionner la carte comme un élément central lors de la saisie

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#218]
Pour faciliter le confort de l'utilisateur lors de la saisie, il serait intéressant de mettre la carte comme un élément central en lui donnant plus de place. Il faudrait également revoir l'organisation des inputs dans la modale.
![gypaète](https://user-images.githubusercontent.com/9743288/78788737-7a374600-79ac-11ea-9af0-4d70851507e3.jpg)

**Comment by samuelpriou** [comment]
Autre proposition :
- Au lieu d'agrandir la modale, il serait je pense plus pratique d'utiliser une nouvelle page qui laisserait la place à la carte et faciliterai l'expérience utilisateur.

**Comment by camillemonchicourt** [comment]
Saisie revue dans la maquette présente sur https://github.com/PnX-SI/GeoNature-citizen/issues/181#issuecomment-646645110
On n'aurait plus une modale mais on utilisera la fenêtre de consultation des données.

**Comment by camillemonchicourt** [comment]
Une révision du formulaire de saisie a été réalisée sur la base de la maquette. Le formulaire de saisie est affiché à la place de la liste des observations existantes.
Une paramètre (``FRONTEND.NEW_OBS_FORM_MODAL_VERSION``) permet de définir si la saisie dans la modale comme précédemment ou dans la barre latérale.
