### ISSUE TITLE
Projet d'administration des données sous QGIS

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#222]
Pour répondre aux besoins de mes collègues en charge des projets utilisant GeoNature-citizen, j'ai créé un projet QGIS permettant la visualisation  et l'administration des données issues d'une instance GeoNature-citizen. Ce projet vient d'être ajouté à ce dépot, dans `/data/qgis_admin`. Il contient notamment un fichier d'instructions ainsi qu'un script bash qui le génèrera automatiquement pour vous en y renseignant les paramètres de connexion à la base de données ainsi que l'URL de l'application permettant ainsi de visualiser les photos chargées par les observateurs.

Tout est ici: https://github.com/PnX-SI/GeoNature-citizen/tree/master/data/qgis_admin

Et une capture d'écran du rendu par défaut, sur le programme en cours de Clermont Agglo.

![1_046](https://user-images.githubusercontent.com/22891423/81223985-3fdeba00-8fe7-11ea-8fc3-c801ddfb67bf.png)

**Comment by camillemonchicourt** [comment]
Fait avec https://github.com/PnX-SI/GeoNature-citizen/pull/221

**Comment by camillemonchicourt** [comment]
Merci pour ce projet et son partage : https://github.com/PnX-SI/GeoNature-citizen/tree/master/data/addons/qgis_admin
