### ISSUE TITLE
Ajouter un nouvel écran permettant d'afficher le détail d'une observation

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#223]
- Une carte pour afficher l'emplacement de l'observation 
- Un slider pour l'affichage des photos 
- Un bloc contenant les informations saisies (comportement principal de l’oiseau, classe d’âge de l’oiseau, nom de l’oiseau, méthode d’identification de l’oiseau), dynamiquement car variables selon le programme.

**Comment by camillemonchicourt** [comment]
Maquetté : 

![image](https://user-images.githubusercontent.com/4418840/85138936-f4553800-b243-11ea-9f37-e7456525ca7e.png)

Maquette vidéo complète sur https://github.com/PnX-SI/GeoNature-citizen/issues/181#issuecomment-646645110
