### ISSUE TITLE
Interface avec iNaturalist, INPN ou autres ?

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#230]
Il serait intéressant de pouvoir s'interfacer avec les grande platefrome :

- Inpn Espces 
- INaturalist 
- Gbif 

Pour bénéficier de la validation peut etre ?

**Comment by camillemonchicourt** [comment]
S'interfacer c'est-à-dire ?
GN-citizen est positionner comme outil de collecte parmi d'autres.
On imagine plutôt GeoNature comme outil de synthèse multisource, avec aussi la validation, la diffusion etc...

**Comment by orovellotti** [comment]
Ok la vision c’est :

citizen >> geonature >> inpn >> gbif 

Il reste donc à améliorer les exports pour pourvoir utiliser les modules import et validation de geoNature?

**Comment by camillemonchicourt** [comment]
Oui un script pour alimenter la synthèse de GeoNature est prévu : https://github.com/PnX-SI/GeoNature-citizen/issues/71

**Comment by orovellotti** [comment]
Ok ça marche on garde l’autre issue

**Comment by lpofredc** [comment]
Je préciserai : 

citizen >> geonature **(validation)** >> inpn >> gbif

**Comment by lpofredc** [comment]
Script d'intégration à GeoNature développé cf. https://github.com/PnX-SI/GeoNature-citizen/issues/71#issuecomment-766751464
