### ISSUE TITLE
Mutualiser les zonages géographiques?

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#245]
Pour les cas d'instances de GeoNature-citizen avec de nombreux programmes, il serait intéressant de mutualiser les zonages géographiques dans une table spécifique, évitant ainsi de recréer le zonage d'un programme à chaque instance et limitant ainsi les manip de création/import de zones géographiques

**Comment by samuelpriou** [comment]
Oui bonne idée !

**Comment by lpofredc** [comment]
Done
