### ISSUE TITLE
Script d'installation sur un serveur avec GeoNature

### ISSUE THREAD

**Issue by AJambon** [PnX-SI/GeoNature-citizen#257]
Nous avons lancé le script d'installation de la nouvelle version sans nous méfier de notre environnement, c'est-à-dire un serveur avec GeoNature déjà installé. 

Première analyse : ça a l'air d'avoir cassé la configuration apache et il semble y avoir des conflits avec taxhub. 

@lpofredc as-tu testé ce contexte ? 

Nous poursuivons sur cette voie de notre côté !

**Comment by AJambon** [comment]
Bonjour ! 

Pour le moment de notre côté nous avons enlevé les commandes d'installation de geonature et taxhub du script, ainsi que la conf apache (qui a été refaite à la main pour le moment).

Nous avons prévu de :
- refaire le script en ajoutant un paramètre pour choisir de tout installer ou seulement citizen,
- Modifier la conf apache pour qu'elle soit compatible avec GeoNature

Mais ce n'est pas encore fait.

Si besoin des scripts faits pour dépanner mais pas paramétrés je peux vous les envoyer par mail. Je posterai ici les scripts finaux lorsqu'ils seront terminés !

**Comment by camillemonchicourt** [comment]
OK, en effet les scripts d'installation packagés de GeoNature et de GeoNature-citizen sont tous les 2 prévus pour se lancer sur un serveur où il n'y a rien dessus.
Donc forcément, en l'état ils peuvent se concurrencer ou se marcher dessus.

Cela serait en effet à affiner si on veut pourvoir lancer ces scripts avec plus de souplesse pour choisir ce qu'on installe ou pas, à partir du script ``install_app.sh``.

**Comment by mvergez** [comment]
Bonjour !

J'ai repris le script `install_app.sh` et j'ai déplacé tout ce qui concerne taxhub dans `install_taxhub.sh`. Ce dernier est exécuté si la variable install_taxhub est différente de 0. J'aimerais également changer ce paramètre en true/false.
J'ai fait cette modification depuis la branche dev. 

Si ça vous convient, je fais une PR.

**Comment by camillemonchicourt** [comment]
Oui intéressant bien sûr pour une PR

**Comment by camillemonchicourt** [comment]
Installation automatique de TaxHub retirée du projet.
Libre à chacun de l'installer manuellement avant GN-citizen, ou alors d'en disposer déjà et de renseigner l'URL de l'API de son TaxHub existant.
