### ISSUE TITLE
Validation d'une observation dans l'ouest

### ISSUE THREAD

**Issue by maxreinhart** [PnX-SI/GeoNature-citizen#261]
Bonjour,

Quand on se trouve dans l'ouest de la France (à l'ouest du méridien de Greenwich), il n'est pas possible de valider l'ajout d'une observation, car le bouton "VALIDER L'OBSERVATION" reste grisé.

Le souci vient de la [regex de validation du formulaire](https://github.com/PnX-SI/GeoNature-citizen/blob/master/frontend/src/app/programs/observations/form/formValidators.ts#L22) pour la géométrie. Quand on se trouve dans l'ouest, la longitude est négative.
J'ai remplacé la regex pour autoriser un "-" sur la longitude et la latitude par la suivante:
`/Point\(-{0,1}\d{1,3}(|\.\d{1,7}),(|\s)-{0,1}\d{1,3}(|\.\d{1,7})\)$/`

**Comment by camillemonchicourt** [comment]
Correction intégrée dans la version 1.0.0.
