### ISSUE TITLE
Quel nom pour GeoNature citizen ?

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#27]
Bonjour à tous,
L'actuel nom GeoNature Citizen est plutôt efficace et clair mais je souhaite ouvrir ce sujet au cas ou il y aurait des idées meilleures. 
Très sincèrement nous n'avons pas d'idées révolutionnaires, en voici quelques une soufflées par une collègue :
GeoNatura'List / Dataxon / Dataction / Biocitizen / Ecodata / Biodata / Tax(i)on(dubois) /Datalheuresilteplait ;)

**Comment by camillemonchicourt** [comment]
Pour moi c'est important que ce soit GeoNature-kelkchose. 
Donc GeoNature-citizen je trouve ça très bien et ça a déjà fait son petit trou.

**Comment by ClarisseBrochier** [comment]
Et GéoNature-citoyen tout bêtement? C'est vrai que je ne suis pas favorable aux mots anglais, qu'il ne me semble pas que la traduction se fasse automatiquement pour la majorité des gens, et qu'en ces temps de colère et de révolte, le mot citoyen prend une importance toute particulière (le deuxième argument n'engage que moi).
Sinon il y a aussi une proposition GeoNature-participatif....

**Comment by ClarisseBrochier** [comment]
Okey bien reçu. Validé pour moi. Et donc à nous de voir ce qu'on affiche sur la page d'accueil de notre appli. Merci Camille pour ces précisions.

**Comment by samuelpriou** [comment]
GeoNature citizen nous convient également comme nom d'outil. 
Merci
