### ISSUE TITLE
Petite coquille sur l'url générant le thumbnail dans le formulaire de saisi

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/GeoNature-citizen#276]
Bonjour,

Une petite remarque.
Au niveau du formulaire de saisie d'une observation, on a un encart affichant une vignette du taxon. 
Cette vignette est générée par taxhub et récupéré avec l'url suivante : https://<DOMAIN>/taxhub/api/tmedias/thumbnail/<id_media>?h=100&v=100

Il me semble que le paramètre 'v' n'a pas de correspondance côté taxhub. Ne serait-ce pas à remplacer par w ?

Voilà tout !

**Comment by camillemonchicourt** [comment]
Si tu testes et confirme le soucis, tu peux faire une PR pour que cela soit intégré dans la prochaine release

**Comment by lpofredc** [comment]
Corrigé ici: 1988938
