### ISSUE TITLE
Vérification de la constante API_TAXHUB sur la branche dev

### ISSUE THREAD

**Issue by xdidx** [PnX-SI/GeoNature-citizen#277]
Bonjour,
je me suis dit qu'il serait plus judicieux de faire mes PRs en me basant sur la branche dev. 
1) Dans un premier temps, j'aimerais savoir si c'est ce que vous préférez, ou si je dois me baser sur la master?

Ensuite, en récupérant la dév, je me suis retrouvé avec un problème lié à cette ligne qui a été modifié le 1er juin:
https://github.com/PnX-SI/GeoNature-citizen/blob/699067934ba5e700b5d47a3f77e99bc6c0354d0e/backend/gncitizen/core/taxonomy/routes.py#L93

Comme la vérification de `current_app.config.get("API_TAXHUB")` n'est plus présente, il ne connait pas la méthode.

2) J'aimerais savoir si c'est volontaire de ne plus utiliser les tables locales pour l'API Taxhub, ou si je peux faire une PR pour ajouter le code qui fonctionnait chez moi (peut etre en mettant le `try catch` autour de toute la condition, contrairement à avant) 

Merci d'avance et bonne soirée/journée !

**Comment by camillemonchicourt** [comment]
Oui il vaut mieux s'appuyer sur la branche "dev" pour les nouveaux développements.

Un objectif est en effet de ne plus dupliquer l'API de TaxHub et son modèle dans GN-citizen (voir le ticket sur le sujet), mais je ne sais pas si c'est le cas ici.
