### ISSUE TITLE
Logo GeoNature citizen

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#28]
Bonjour,
Puisque nous avons le nom de l'application (GeoNature citizen), il faudrait commencer à réfléchir à un logo.
La version professionnelle/associative de GeoNature s'oriente vers ce [logo](https://github.com/PnX-SI/GeoNature/issues/346#issuecomment-458056712).
Il serait intéressant de conserver la couleur noire, la police de caractère et d'insérer un origami en lieu et place du colibri et de la fleur. Je pensais à la[ Saxifrage à fleurs nombreuses](http://www.mercantour-parcnational.fr/fr/des-connaissances/le-patrimoine-naturel/une-extraordinaire-richesse-floristique/saxifrage-fleurs). Qu'en pensez vous ?

**Comment by DonovanMaillard** [comment]
Bonjour,

Pourquoi ne pas garder le principe de geonature atlas, c'est à dire ne pas 
avoir de logo de l'application sur ce portail et avoir seulement le logo de la structure et/ou du portail lui même ?

 
Je dis ça car il est compliqué de prévoir l'usage de l'outil. Et pour ces portails destinés au grand public il est important pour toute structure d'être cohérent sur ses logos et sa communication.

Par exemple avoir une fleur en logo sur un outil grand public pour le pôle sinp invertébrés de la région est incohérent. 
Ce qui se justifie sur l'outil pro par ailleurs car les pros savent qu'ils viennent sur un outil "naturaliste" au sens large. Ce n'est que mon avis :)

**Comment by camillemonchicourt** [comment]
Oui on va pas afficher le nom technique de l'outil.

Quel serait l'usage pour un logo GN-citizen ?

**Comment by samuelpriou** [comment]
Nous n'allons effectivement pas afficher le nom technique de l'outil. Les différentes maquettes réalisées montre un [logo](https://github.com/PnX-SI/GeoNature-citizen/issues/6). Comme le fait remarquer justement @DonovanMaillard il faut pouvoir intégrer à minima le logo de sa structure ou un logo pour faciliter la communication sur l'outil.

**Comment by DonovanMaillard** [comment]
Oui @samuelpriou , mais du coup c'est un logo propre à chaque utilisateur. 
A mon sens pas besoin de prévoir un logo pour l'application en elle-même (comme gn atlas qui est livré avec le logo du PNE pour exemple, mais qui du coup est remplacé avant d'être mis en production par chacun).

**Comment by camillemonchicourt** [comment]
L'application générique n'a pas forcément besoin de logo. 
Comme évoqué pour le nom et comme pour l'atlas, chacun donnera un nom local à sa déclinaison de l'outil qui ne sera bien sur pas GeoNature-citizen. 
Chacun utilisera ses couleurs et le logo de sa structure pour son instance de GeoNature-citizen. 

Comme pour GeoNature-atlas, l'outil sera éventuellement juste mentionné pour info en pied de page ou dans les crédits. 

Le logo pourra éventuellement être utilisé pour des présentations de l'outil. 
Dans ce cas, on pourrait décliner celui de GeoNature mais il n'y pas de besoin réel. 
Celui proposé par défaut est sympa comme ça je trouve. Et ça change de nos espèces vues et revues avec un clin d’œil pour la Camargue. 

![logo](https://user-images.githubusercontent.com/4418840/51870848-10a5bb80-2355-11e9-9059-adcdbad7f665.png)
