### ISSUE TITLE
Module administration - Suppression des observations par l'administrateur

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#284]
Il serait intéressant que le module d'administration permette la suppression d'observations rattachées à un compte utilisateur lorsque celles-ci sont erronées.

**Comment by mvergez** [comment]
Bonjour,
Justement j'ai remarqué la même chose et j'allais ouvrir une issue puis une PR. J'essaie de la faire aujourd'hui.

En attendant, voici les modifications que je compte faire : 

# Etape 1
Dans https://github.com/PnX-SI/GeoNature-citizen/blob/197e64b8e73eaafb034833ac93719ac6102c89c9/backend/gncitizen/core/commons/admin.py

Ajouter le code suivant : 
```python
class ObservationView(ModelView):
    create_template = "edit.html"
    edit_template = "edit.html"
```

# Etape 2
Dans https://github.com/PnX-SI/GeoNature-citizen/blob/master/backend/gncitizen/core/commons/routes.py

Importer `ObservationView` comme ceci : 

```python
from gncitizen.core.commons.admin import (
    ProjectView,
    ProgramView,
    CustomFormView,
    UserView,
    GeometryView,
    ObservationView
)
```

Puis ajouter la ligne suivante : 

```python
admin.add_view(
    ObservationView(ObservationModel, db.session, "Observations")
)
```

Et normalement c'est tout ! J'ai réussi à supprimer des observations et à modifier certaines informations mais j'ai pas tout testé. Si tu as le temps n'hésite pas à me faire un retour !

**Comment by samuelpriou** [comment]
@mvergez. Ok j'essaie de tester cela.
Merci !

**Comment by samuelpriou** [comment]
@mvergez. Une fois le code ajouté faut il lancer des commandes spécifiques ?

**Comment by mvergez** [comment]
@samuelpriou normalement non, juste `sudo supervisorctl restart gncitizen_api` (si tu passes par supervisor)

**Comment by samuelpriou** [comment]
Cela fonctionne très bien ! Merci @mvergez

**Comment by lpofredc** [comment]
mergé dans PR #285

**Comment by camillemonchicourt** [comment]
Évolution intégrée dans la version 1.0.0.
