### ISSUE TITLE
[Supervisor] Le processus du serveur ssr (frontend) ne se stoppe pas après supervisorctl stop

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature-citizen#286]
**Contexte :**
Le Frontend de citizen est lancé par le script `start_server.sh` (`npm run serve:ssr`) via supervisor

**Problème :**
J'ai remarqué qu'en faisant la commande suivante `sudo supervisorctl stop gncitizen_front` les processus suivants sont toujours présents : 
- sh -c node dist/server
- node dist/server

Et je dois donc les kill à la main avant de refaire un `sudo supervisorctl start gncitizen_front`. Sinon une erreur npm apparait disant que le port est déjà pris.

J'ai trouvé une solution que je vais renseigner ci-dessous.

Avez-vous rencontré le même problème ?

**Comment by mvergez** [comment]
**Solution** (?): 

Modifier le fichier `/etc/supervisor/conf.d/gncitizen_frontssr-service.conf` en ajoutant les deux lignes suivantes : 

```
stopasgroup=true
stopsignal=QUIT
```

**Comment by lpofredc** [comment]
Corrigé ici: b04a103cea2011b3377b273f0e5a732becb55b9a
