### ISSUE TITLE
MCD GN-citizen

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-citizen#3]
![2018-07-18-mcd](https://user-images.githubusercontent.com/4418840/42884774-7eb057a6-8a9f-11e8-90a5-c9274a000ec0.jpg)

Première réflexion sur le MCD. 
En orange les référentiels avec lesquels l'application interagirait. 
En vert les schémas de GeoNature avec lesquels elle pourrait communiquer. 

A voir néanmoins comment permettre d'utiliser cette application indépendamment de GeoNature.

**Comment by camillemonchicourt** [comment]
A voir par contre si on a plusieurs programmes de collecte citoyenne, alors il faudra ajouter une table ``gn_citizen.t_programs`` avec une FK dans ``gn_citizen.t_observations`` y faisant référence. 

``gn_citizen.t_programs`` contiendrait un ``id_program``, ``program_name``, ``active`` (boolean), ``description``, ``id_list_taxons``

**Comment by camillemonchicourt** [comment]
Après discussion : 
- On s'appuierait bien sur TaxHub, ses listes et son API
- On ne s'appuierait pas sur UsersHub dans un premier temps car c'est complexe et pas mur. On aurait donc une table ``t_users`` intégrée à ``gn_citizen``
- A voir si on utilise le schéma ``ref_geo`` dont on n'aurait pas besoin de tout mais qui apporte des fonctionnalités et une homogénéité intéressantes : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/ref_geo.sql
- On pourrait se brancher aux différents schémas de GeoNature sans l'imposer (validation, synthèse, métadonnées...)
- Du coup, on intégrerait une gestion des médias des observations dans ``gn_citizen`` pour ne pas imposer une dépendance à GeoNature

**Comment by camillemonchicourt** [comment]
Ce n'est pas un module GeoNature. 
C'est un application indépendante de GeoNature mais connectable à GeoNature. Comme GN-atlas mais au lieu d'être en aval, elle est en amont. 

Donc c'est plutôt le cas 2, mais comme GN-atlas il dépendra de TaxHub (de manière optionnelle mais fortement conseillée pour pouvoir gérer les médias, les descriptions, les listes...) mais pas de GeoNature. 

En effet la synthèse aura une API donc on a imaginé l'utiliser de l'extérieur (pour des get mais aussi des post, update, delete avec un token). Cependant, dans notre cas, si quelqu'un veut utiliser GN-citizen avec GeoNature, on a plutôt imaginer intégrer son schéma ``gn_citizen`` dans la BDD de GeoNature et faire un trigger vers la synthèse comme depuis les autres sources. En plus de simplifier les choses, cela permettrait aussi de pouvoir bénéficier des tables verticales d'historique, de validation...

Concernant les données dans la Synthèse, comme beaucoup de données partenaires, elles n'auront pas de CRUVED, et peu de nomenclatures renseignées que l'on mettra alors à ``Non renseigné``, à moins d'avoir une valeur globale certaine (comme pour ``StatutObservation=Présent`` et quelques autres). Comme les données partenaires elles seront associées à des jeux de données, des cadres d'acquisition, des sources...

Pour le moment, pour faire simple, on a prévu de pouvoir ne pas imposer l'authentification, voire même de la désactiver totalement. Et pour limiter les dépendances, de ne pas fonctionner avec UsersHub mais avec une gestion interne des utilisateurs. Néanmoins pour une meilleure intégration avec GeoNature, pour bénéficier d'un ``id_role``, voire d'un ``id_organisme``, cette piste pourra être réétudiée dans un second temps, avec les conséquences que cela entraîne. Pour le moment, ce n'est pas mur.

**Comment by camillemonchicourt** [comment]
Actuellement le MCD implémenté est https://github.com/PnX-SI/GeoNature-citizen/blob/dev/mcd.png

**Comment by lpofredc** [comment]
Merci @camillemonchicourt , C'est un MCD provisoire en cours de construction. Vu pour la proposition du shema ref_geo. En effet, autant partir sur la même base.

**Comment by camillemonchicourt** [comment]
Oui OK, super. Bravo pour l'avancement des développements.

**Comment by lpofredc** [comment]
Nouvelle ![Mise à jour du MCD ](https://github.com/PnX-SI/GeoNature-citizen/blob/dev/mcd.png)

**Comment by camillemonchicourt** [comment]
OK merci.
Il ne devrait pas y avoir de lien entre ``sights`` et ``li_municipalities``. 
``li_municipalities`` est une extension de ``l_areas``. Donc ça devrait être l'inverse. Un lien entre ``sights`` et ``l_areas``. Et ``li_municipalities`` étant lié à ``l_areas``, elle permet d'avoir des infos complémentaires sur la commune quand le zonage est de type "Commune".

**Comment by lpofredc** [comment]
Dernière version de mcd
![gnc_core](https://user-images.githubusercontent.com/22891423/50802842-60f6a400-12e8-11e9-8b28-87acc77785b5.png)

**Comment by lpofredc** [comment]
Dernière mise à jour  du MCD.
Ajout d'une table des correspondances des médias avec les observations pour plus de souplesse (en prévision de pouvoir poster plus de média par observation). Table automatiquement alimentée par la fonction  `save_upload_files`.

![mcd](https://user-images.githubusercontent.com/22891423/53405124-6e124400-39b7-11e9-8aee-c5e836b21d56.png)

**Comment by camillemonchicourt** [comment]
Pour les médias, ne faut-il pas ajouter une légende (title), un auteur et éventuellement une source et une licence ?

**Comment by lpofredc** [comment]
Si, en effet:
* Pour la légende, on peut par exemple le générer à partir du nom d'espèce, 
* l'auteur, plus complexe du fait des deux cas de figure (enregistré ou non)... ça soulève de nombreuses questions... Notamment la gestion en cas de suppression du compte.
* source: nom du programme?
* licence: défini globalement pour le portail dans les CGU de la plateforme ?

**Comment by camillemonchicourt** [comment]
Pour moi ce sont tous des champs texte optionnels : 
- La légende peut être plus fine que le nom d'espèce (avec le lieu, le contexte...). 
- L'auteur du média est pas forcément le même que celui qui saisit l'observation
- Source, c'est différent du programme, c'est l'éventuelle structure à l'origine du média (en complément de l'auteur)
- Pour le licence, je ne sais pas si le portail peut l'imposer globalement, d'autant plus si le média a déjà une licence existante. 

Mais tout ça est peut-être hors cadre pour des médias illustrant une observation.
