### ISSUE TITLE
Afficher toutes les données des visites dans le détail d'un site

### ISSUE THREAD

**Issue by nobohan** [PnX-SI/GeoNature-citizen#302]
La page qui affiche le détail d'un site (`/programs/{id_program}/sites/{id_site}`) affiche les détails de la dernière visite uniquement, tandis que toutes les photos disponibles sont affichées. 

Est-ce voulu? 

Ne faudrait-il pas pouvoir afficher tous les rapports de visite? 

Ma proposition:
- modifier le point d'API `get_site` pour servir toutes les visites
- adapter le front pour afficher toutes les visites au lieu de la dernière

**Comment by camillemonchicourt** [comment]
Oui en effet il faudra pouvoir consulter toutes les visites du site.

**Comment by nobohan** [comment]
Bonjour, j'ai soumis une PR dans ce sens.

**Comment by camillemonchicourt** [comment]
Intégré dans la 0.99.4
