### ISSUE TITLE
Erreur 405 sur POST api/token_refresh (performTokenRefresh)

### ISSUE THREAD

**Issue by nobohan** [PnX-SI/GeoNature-citizen#305]
Nous avons une erreur étrange avec notre installation de biomap (https://biomap.champs-libres.be/) ainsi qu'en développement en local (sur des containers docker). 

Lors de l'ouverture d'une page, le message `[AuthInterceptor.performTokenRefresh] error "[object Object]"` apparait dans la console JS. La raison est que la requête POST /api/token_refresh ne passe pas et renvoie une erreur 405. 

Malheureusement, je n'arrive pas à reproduire l'erreur de manière systématique. Mais elle apparait chez moi en local et sur le site https://biomap.champs-libres.be/ ainsi que chez d'autres personnes, probablement après une connexion avec son nom d'utilisateur. En supprimant le localStorage du navigateur, l'erreur disparait. 

C'est fort bloquant car plusieurs liens de l'application sont inutilisables après cette erreur. Et sans supprimer le localStorage (ou passer sur un autre navigateur), on ne peut plus utiliser l'application.

**Comment by nobohan** [comment]
Je réactive ceci, après avoir vu que d'autres ont travaillé dessus: https://github.com/PnX-SI/GeoNature-citizen/commit/3c0ae49f58562efca8f6678182a3417df1d09e46

**Comment by camillemonchicourt** [comment]
A priori corrigé dans la version 1.0.0
