### ISSUE TITLE
Erreur pour installer postgresql

### ISSUE THREAD

**Issue by xdidx** [PnX-SI/GeoNature-citizen#313]
Bonjour,
J'installe l'environnement sur une nouvelle machine et j'obtiens une erreur que je n'ai pas l'impression d'avoir déjà eu.
En executant `sudo apt install postgresql-10`, j'ai 
`Les paquets suivants contiennent des dépendances non satisfaites :
 postgresql-10 : Dépend: libicu57 (>= 57.1-1~) mais il n'est pas installable
                 Recommande: sysstat mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».`

Une idée d'où peut provenir le problème ? Faut-il forcément downgrader la version de l'OS ? (Je suis sur Ubuntu 20.04. J'avais déjà Ubuntu sur l'ancienne machine, mais je ne suis pas sûr de la version)

Merci d'avance et bonne journée !

**Comment by lpofredc** [comment]
Bonjour,
Merci pour l'info, en effet, il faut revoir et nettoyer la doc car le script d'installation se charge déjà d'installer postgreSQL et de manière plus générique, sans numéros de versions.

Par défaut, l'installation s'appuie sur la version fournie par l'OS. 

https://github.com/PnX-SI/GeoNature-citizen/blob/2f937ff8e415216af0050fc135019ea600fa9c37/install/install_app.sh#L60

**Comment by xdidx** [comment]
J'ai essayé avec les versions 10-11-12-13 et 14, et sans version (ce qui correspond à la version 14), toujours le même problème avec libicu57.
J'ai vraiment du mal à comprendre, car je n'ai pas eu le problème avec l'autre Ubuntu en version 20.04 (j'ai vérifié la version) il y a quelques mois...

N'hésitez pas à fermer l'issue dans quelques jours si personne n'a de réponse.

Rien à voir: il y a deux fois `postgresql` dans la ligne citée.
