### ISSUE TITLE
[maj] 0.99.3 -> 0.99.4 - Erreur

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/GeoNature-citizen#317]
Bonjour,

Je viens d'essayer de réaliser une mise à jour de citizen V0.99.3 vers V0.99.4.

Je vous partage ma procédure (en espérant qu'il n'y ai pas de louper dans la restitution des actions)

```
$ wget https://github.com/PnX-SI/GeoNature-citizen/archive/refs/tags/v0.99.4-dev.zip
$ mv gncitizen gncitizen_old
$ unzip v0.99.4-dev.zip
$ mv GeoNature-citizen-0.99.4-dev gncitizen

# récupération et modification fichier de configuration backend
$ cp  gncitizen_old/config/default_config.toml gncitizen/config/
$ vim gncitizen/config/default_config.toml

Ajouter :
-	Ligne 28 :
o	HCAPTCHA_SECRET_KEY='' (l. 28)
-	Ligne 55 :
NO_VALIDATION_HTML_TEMPLATE = '''<p> Bonjour,</p><br /><p>Nous vous confirmons que votre compte a bien été créé.</p>
     <p>Nous vous souhaitons la bienvenue sur notre site.</p><br />
     <p>Cordialement.</p>
    '''

# récupération et modification fichier de configuration frontend
$ mv gn_citizen/frontend/src/conf/app.config.ts gn_citizen/frontend/src/conf/app.config.ts.OLD
$ cp gn_citizen_old/frontend/src/conf/app.config.ts gn_citizen/frontend/src/conf/app.config.ts
$ vim gn_citizen/frontend/src/conf/app.config.ts

Ajouter :
-	Ligne 5 :
o	HCAPTCHA_SITE_KEY : null
-	Ligne 14 :
o	NEW_OBS_FROM_MODAL_VERSION : true
-	Ligne 60 :
o	taxonDisplayImageWhenUnique : true,
Modifier :
-	Ligne 26
o	Signup : "always"

# Création du dossier media
$ cp -r gncitizen_old/media gncitizen/

# récupération des assets
$ mv gncitizen/frontend/src/asset gncitizen/frontend/src/asset_old
$ cp -r gncitizen_old/frontend/src/asset gncitizen/frontend/src/

# Installation des dépendances
$ sudo apt update && sudo apt -y install python2.7 git gcc curl gunicorn python-setuptools lsb-release apt-transport-https wget
$ sudo apt -y install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev curl libbz2-dev
$ sudo apt -y install apache2 python-dev libpq-dev libgeos-dev supervisor unzip virtualenv libcurl4-openssl-dev libssl-dev
$ sudo apt -y install build-essential libglib2.0-0 libsm6 libxext6 libxrender-dev
$ sudo apt install python3 python3-dev python3-pip -y

$ pip3 install --upgrade pip
$ python3 -m pip install poetry --user

# Construction du frontend
$ cd gn_citizen/frontend/
$ npm install
$ npm run build
$ cd ..

# Installation des dépendances du backend
$ cd backend/
$ poetry install

$ sudo supervisorctl restart citizen_api
```

Suite à ça, je rencontre une erreur peu explicite (pour moi) lorsque j'essaye d'afficher la page d'accueil de Citizen. Plus exactement lors de l'appel de la route api/programs qui me retourne : 
```
{
    "message": "<ColumnProperty at 0x7feab8ab7048; is_active>"
}
```

Je suis bloqué à ce stade.
Auriez-vous des pistes de résolution ?

Merci par avance.

**Comment by PNPyrenees** [comment]
Échec également en partant d'une VM vierge (en ubuntu server 18.04 ou 20.04)

Le script d'installation ne me créé pas la base de données et quand je relance le superviseur, il me sort des librairies manquante :

18.04 :
```
- No module named pathlib
$ pip3 install pathlib
```
Mais le problème persiste

20.04 :
```
- No module named flasgger
$ pip install flasgger
- No module named 'flask_admin'
$ pip install flask_admin
-  No module named flask_ckeditor
$ pip install flask_ckeditor
- No madule named flask_jwt_extended
$ pip install flask_jwt_extended
- No madule named flask_sqlalchemy
$ pip install flask_sqlalchemy
- No madule named toml
$ pip install toml
- No madule named flask_cors
$ pip install flask_cors
- No madule named geoalchemy2
$ pip install geoalchemy2
- No madule named utils_flask_sqla_geo
$ pip install utils_flask_sqlalchemy
```
Le dernier paquet utils_flask_sqlalchemy n'est pas trouvé

Je sèche complet !

**Comment by QuentinJouet** [comment]
Bonjour,

J'ai un problème similaire en essayant de mettre à jour l'instance utilisée par la LPO isère.

La méthode program.as_dict() lève cette erreur :

`KeyError: <ColumnProperty at 0x7fdde7983048; logo>`

Avez-vous trouvé une solution ?

**Comment by camillemonchicourt** [comment]
Je ne sais pas si le soucis est lié, mais je vois que GeoNature-citizen utilise un fork de utils_flask_sqlalchemy qui n'est peut-être pas à jour ou a un soucis : https://github.com/PnX-SI/GeoNature-citizen/blob/master/backend/requirements.txt#L46 ?

**Comment by mvergez** [comment]
Effectivement bien vu, en Python 3.9, j'avais dû changer le pyproject.toml avec cette ligne `utils-flask-sqlalchemy = {git = "https://github.com/PnX-SI/Utils-Flask-SQLAlchemy"}`.

Ou lancer la commande `poetry add git+https://github.com/PnX-SI/Utils-Flask-SQLAlchemy`

**Comment by camillemonchicourt** [comment]
OK en effet le dépôt officiel dispose d'une version récente compatible Python 3.9 : https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/releases
Alors que le fork est resté sur une ancienne version.

Donc il faudrait modifier le ``requirements.txt`` pour utiliser le dépôt officiel et non pas le fork.

**Comment by QuentinJouet** [comment]
Ok merci, mais j'étais en python 3.6, dois-je nécessairement passer en python 3.9 ?

**Comment by QuentinJouet** [comment]
Ok merci c'est bon, j'ai modifié requirements.txt et gardé python 3.6, le problème est résolu !

**Comment by camillemonchicourt** [comment]
OK donc à modifier dans la prochaine version, mais avec ``poetry``, je ne sais pas où il faut modifier cela, je laisse les connaisseurs modifier cela pour la prochaine release.

**Comment by mvergez** [comment]
C'est fait ici : https://github.com/PnX-SI/GeoNature-citizen/pull/321

**Comment by camillemonchicourt** [comment]
Corrigé dans la 1.0.0
