### ISSUE TITLE
Installation de TaxHub automatique

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/GeoNature-citizen#322]
Bonjour, 

@mvergez et @Julien-Gr4z ont repris l'installation de GeoNature-citizen dans le cadre d'une prestation avec le PN du Mercantour dans l'optique d'une V1.0. Cette reprise s'est accompagnée d'une réflexion sur les dépendances au schéma taxonomie ainsi qu'à la table l_areas du ref_geo. 
Cette installation a été testée et semble maintenant fonctionnelle cf #321. Toutefois, une ligne permet d'installer automatiquement TaxHub au besoin (dont la version est paramétrable). 
Maxime, et je partage son avis, trouve que cela crée une dépendance à TaxHub dont l'installation est amenée à évoluer assez régulièrement, or maintenant, nous utilisons seulement son API. 

Ne serait-il pas envisageable de renvoyer à la documentation d'installation de TaxHub et que celle-ci soit manuelle ? 

Merci pour vos avis,

**Comment by samuelpriou** [comment]
Bonjour à tous,
Oui il serait finalement plus simple d'installer TaxHub manuellement pour casser la dépendance.

**Comment by camillemonchicourt** [comment]
Il y a une dépendance applicative.
On ne peut pas utiliser GeoNature-citizen sans disposer de TaxHub.
C'était donc intéressant de simplifier l'installation de TaxHub pour ceux qui veulent juste GeoNature-citizen, un peu comme on a le ``install_all`` dans GeoNature.
Mais si ça complique trop l'installation, tant pis, les administrateurs l'installeront à part manuellement.

**Comment by Adrien-Pajot** [comment]
Merci pour ces retours. Sans compliquer l'install je pense que ça permet que les admin comprennent bien ce qu'ils font avec TaxHub, au lieu que ce soit fait automatiquement. On en discute avec @lpofredc et on vous dira ce qu'on aura fait

**Comment by camillemonchicourt** [comment]
Depuis la version 1.0.0 on ne gère plus automatiquement l'installation de TaxHub.
A chacun de l'installer manuellement avant si il ne dispose pas déjà de cet outil.

La dépendance au niveau BDD a été grandement réduite pour s'appuyer au maximum sur l'API de TaxHub, mais elle a du être gardée à minima à cause du module de badges qui en dépend.
Évoqué dans https://github.com/PnX-SI/GeoNature-citizen/issues/236#issuecomment-2003684219.
