### ISSUE TITLE
Appel à Taxhub directement depuis le front pour récupérer la liste des taxons

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature-citizen#324]
### Problématique
Comme évoqué dans #323, il serait plus judicieux de supprimer la route `/taxonomy_lists/<id_liste_taxhub>/species/` du backend de citizen et de la remplacer par un appel Taxhub directement : `/api/biblistes/taxons/<id_liste_taxhub>`.

A première vue il manquerait uniquement le media_id à récupérer auprès de Taxhub (donc en appelant une autre route)

### Proposition d'implémentation
Compléter le service Taxhub déjà présent pour éviter des routes en dur dans le code

---

J'essaie de faire une PR

**Comment by TheoLechemia** [comment]
Salut,
Si c'est pour proposer une liste avec un typeahead (autocomplété), la route est plutôt celle-ci : 
https://github.com/PnX-SI/TaxHub/blob/master/apptax/taxonomie/routestaxref.py#L341
Et on privilégie maintenant la recherche via le "code_liste", plutôt que "l'id_list" qui est un serial.

**Comment by mvergez** [comment]
Salut Théo,
Merci beaucoup pour la route, je vais partir sur celle là.
Pour l'id_list je pense qu'il faudra changer un peu plus de choses dans Citizen.
