### ISSUE TITLE
Validation des observations avant affichage

### ISSUE THREAD

**Issue by jonath35** [PnX-SI/GeoNature-citizen#325]
Bonjour,

Je suis confronté à une demande qui m'avait paru simple en amont de mon travail mais qui finalement ne l'est pas.

Est-il possible de ne pas afficher une observation sur l'interface de GNcitizen tant que celle-ci n'a pas été validée ?

Je pensais à l'utilisation d'un trigger (instead of) sur la table t_obstax mais le front me remonte une erreur.

Avez-vous déjà été confronté à cette question ?

D'une façon générale, j'aimerais savoir s'il y a des modalités de prestation avec l'éditeur pour des besoins spécifiques de développement ?

Merci d'avance

**Comment by camillemonchicourt** [comment]
Bonjour,

Il n'est pas prévu de Validation dans GeoNature-citizen car il s'agit avant tout d'un outil de collecte citoyenne, de remontée et de partage d'observations, sans filtre.

Par contre l'outil est intégrable dans l'écosystème plus large de GeoNature qui lui dispose d'un module de Validation, où les données provenant de GeoNature-citizen peuvent être une source de la Synthèse parmi d'autres (https://github.com/PnX-SI/GeoNature-citizen/issues/71).

Si il faut ajouter un module Validation dans GeoNature-citizen, pourquoi pas mais celui-ci devrait être très simple et basique, et surtout activable/désactivable, car tous les utilisateurs ne souhaiteront pas valider les données directement dans GeoNature-citizen, et au contraire que chaque saisie soit directement partagé avec tout le monde pour ne pas freiner le partage et la contribution à un mécanisme de validation qui est souvent long.

-------------------------------

GeoNature-citizen est un logiciel libre et il n'y a pas UN éditeur.
Par contre, plusieurs prestataires informatiques proposent leurs services d'accompagnement, d'hébergement ou de développement de GeoNature-citizen.

Les informations commerciales n'ont pas leur place dans les tickets, mais vous pourrez trouver des prestataires travaillant sur GeoNature en cherchant sur un moteur de recherche, ou me contacter par le contact présent sur https://geonature.fr, ou encore laisser un moyen de vous contacter ici si un prestataire souhaite vous proposer ses services.

**Comment by jonath35** [comment]
Merci pour votre retour !
Désolé pour la question commerciale mais merci tout de même pour votre réponse.

Concernant la validation. Peut être que je peux modifier une requête utilisée par citizen (backend/frontend) pour filtrer les résultats sur un booléen que j ajouterai dans la table t_obstax?
C est un peu bricolage j en convient mais si cela pourrait me dépanner.

Merci

**Comment by camillemonchicourt** [comment]
Pas de soucis pour la question sur les prestataires.

> Concernant la validation. Peut être que je peux modifier une requête utilisée par citizen (backend/frontend) pour filtrer les résultats sur un booléen que j ajouterai dans la table t_obstax?

Oui vous pouvez tenter ça sur votre instance déjà pour tester et avancer de votre côté.
Vous ajouté un champs booléen ``valid`` avec une valeur par défaut à ``False`` renseigné automatiquement dans la BDD, et ensuite filtrer la requête qui renvoie les observations sur ce champs en prenant que les ``True``.

Mais c'est bricolages en effet, car c'est sur votre instance uniquement, alors qu'il vaudrait mieux une évolution au niveau de l'outil GeoNature-citizen partagé, que cela soit bien identifié et géré par les modèles Python du projet, et que l'administrateur puisse valider les données directement dans l'interface.

Je dirai naïvement que ça se passe au niveau des routes de l'objet "observation" : https://github.com/PnX-SI/GeoNature-citizen/blob/dev/backend/gncitizen/core/observations/routes.py
Mais je n'y connais rien en Python.

**Comment by camillemonchicourt** [comment]
Module de Validation optionnel intégré dans la version 1.0.0 de GeoNature-citizen. 
Voir https://github.com/PnX-SI/GeoNature-citizen/issues/358
