### ISSUE TITLE
saisie hors zone géographique

### ISSUE THREAD

**Issue by jonath35** [PnX-SI/GeoNature-citizen#332]
Bonjour,

Je constate que malgré la définition d'une zone géographique dans la back office (geojson ou kml), la saisie en dehors de la limite est possible.
Est-ce normal ?
J'ai essayé avec un simple rectangle et le résultat est le même. Je ne vois pas où ce situe le paramétrage s'il y en a un.

Merci d'avance.

**Comment by lpofredc** [comment]
Pb résolu
