### ISSUE TITLE
[Installation] Version de wtforms

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature-citizen#334]
Bonjour,

### Contexte
En refaisant une installation chez moi avec Docker, j'ai remarqué que l'interface admin ne permettait plus de créer des objets (par exemple une zone géographique). Une erreur de ce type apparaissait dans le backend : 
```
TypeError: process() got an unexpected keyword argument 'extra_filters'
```
### Raison du problème
En cherchant un peu, j'ai trouvé cette issue : https://github.com/flask-admin/flask-admin/issues/2142 qui montre un problème de flask-admin notamment avec la version 3.0.0+ de wtforms.

Il s'avère que Flask-admin se dit compatible avec toutes les versions de wtforms car aucune version n'est mise dans le `setup.py`: (https://github.com/flask-admin/flask-admin/blob/18d28e8123bf1f787b91d42ad51ecaaf3e8c8cc0/setup.py#L40-L42). D'après l'issue d'au dessus ce n'est pas le cas.

### Proposition de solution
Mettre en dur la version 2.3.3 de wtforms dans https://github.com/PnX-SI/GeoNature-citizen/blob/b9d72d5d022c77b10ed43de782dba9b979ac3211/backend/pyproject.toml comme ceci : `wtforms = "^2.3.3"`
J'ai testé ça fonctionne. Ceci le temps que flask-admin soit mis à jour (actuellement en version 1.5.8).

Je ferai une PR dans ce sens ou l’inclurai dans une autre PR d'amélioration de docker qui pourrait (j'aimerais bien) conduire à un GitHub action publiant les images docker de Citizen pré-construites

**Comment by camillemonchicourt** [comment]
Oui c'est aussi ce qu'on a du faire récemment dans GeoNature : https://github.com/PnX-SI/GeoNature/commit/a278684ab278436c2b53c1a0e3aeed9370955111

**Comment by mvergez** [comment]
Merci @camillemonchicourt pour l'info ! J'avais pas vu passer ça sur GeoNature, je regarderai plus attentivement dans le code la prochaine fois.

**Comment by lpofredc** [comment]
Pb résolu par la maj des dépendances
