### ISSUE TITLE
Module sites intégré dans le coeur de la plateforme ?

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#34]
Dans le cadre d'un projet de recensement participatif des mares de l'agglomération de Grenoble, la LPO Isère et la Métropole de Grenoble ont lancé le développement d'un module "mares" dont la généricité pourra également s'appliquer à d'autres types de sites (arbres remarquables, bâtis, etc.). C'est ascan.io et @jolleon qui ont en charge ce projet.

Au regard de la complémentarité de cette approche "sites" avec celle d'observations opportunistes, je propose ce module, initialement prévue en module externe ([gnc_site](https://github.com/LPOAgirPourLaBiodiversite/gnc_sites)), intègre directement le cœur de l'application GeoNature-citizen. Le choix d'une approche "observation" ou une approche "site" sera alors défini au niveau du programme.

## L'objectif de cette plateforme "site"

Il est de répertorier des sites (dans un premier temps des mares):
* Pour chaque site, de pouvoir saisir des relevés à différentes dates (= visites, pour caractériser par exemple l'état de la mare) ;
* Pour chaque site, de pouvoir saisir des observations d'espèces à différentes dates (dans la table des observations du module principal GeoNature-citizen).

### Pour les visites

Pour plus de généricité et réduire les temps de développements pour cette première version, il a été choisi que le formulaire soit automatiquement généré à partir d'une structure JSON stockée en bdd dans une table "types de sites". Ainsi, chaque type de site pourra disposer d'un formulaire adapté.
Cette fonction devrait s'appuyer sur [Angular6-json-schema-form](https://github.com/hamzahamidi/Angular6-json-schema-form) ou sur [ngx-formly](https://github.com/ngx-formly/ngx-formly).

De même, les données relevées lors des visites seront dans un premier temps stockées au format JSONB en bdd. Elles pourront être présentées sous la forme d'une table structurée par vues.

### Pour les observations

La saisie des observations s'appuiera sur le formulaire en cours de développement dans le coeur de GeoNature-citizen. le lien entre les observations et les sites se fera par une table intermédiaire de correspondances.
  
Merci pour vos retours rapides.

**Comment by jolleon** [comment]
Stocker la structure elle même dans la BDD va compliquer les choses. Je pense qu'il vaut mieux partir sur un ou des fichiers JSON (avec la structure en json schema) qui vivent à coté du code:
- la structure va être assez complexe (près d'une vingtaine de champs avec des types divers) donc il vaut mieux pouvoir travailler dessus et l'auditer comme du code
- en fonction des modules frontend choisis certains risquent d'avoir besoin de cette structure dans un fichier
- l'avoir dans un fichier permettra aussi de l'integrer facilement avec des libs coté serveur, par exemple pour validation des inputs ou auto-générer les docs swagger

**Comment by jolleon** [comment]
Pour ce qui en est de construire le module mares directement dans GNC vs dans un module externe "sites", le mettre directement dans GNC me parait être un peu plus simple, mais je n'ai pas tout le contexte sur l'ensemble du projet :)

**Comment by camillemonchicourt** [comment]
Oui ça semble plus pertinent de mettre ça dans le cœur car on aura 2 types de programmes : 
- Ceux consistant à relever des observations d'espèces (BDD définie)
- Ceux consistant à inventorier des sites avec des informations diverses (observations d'espèces sur site et autres)

- Il est important de garder une approche simple mais aussi générique. 
- Le fait de définir la structure des données des programmes SITES de manière souple et générique est intéressante, mais il faut qu'elle reste simple à mettre en œuvre pour les structures qui déploieront GeoNature-citizen

Enfin, il est important que la partie PROGRAMME ESPÈCES en cours de développement ne soit pas complexifiée ni perturbée. 

De ce que je comprends : 
- Il faut ajouter un champs type dans la table ``t_programs`` pour définir si il s'agit d'un programme SITES ou ESPECES. Et dans le cas d'un programme SITES, il faut aussi pouvoir définir le modèle de données JSON. Où ça ?
- La page d'un programme va être différente si on est dans un programme SITES ou ESPECES (principalement la partie qui affiche les données)
- Le formulaire de saisie d'observations va être commun et prédéfini pour les programmes ESPECES, tandis qu'il sera généré à la volée par le schéma JSON pour les programmes SITES

Très bien pour la partie PROGRAMMES SITES, mais à voir comment ne pas alourdir la partie PROGRAMME ESPÈCES en cours de développement.

**Comment by camillemonchicourt** [comment]
OK

**Comment by samuelpriou** [comment]
Bonjour,

Dans la mesure où les développements de la partie "PROGRAMME SITES" n'interfèrent pas les devs de la partie "PROGRAMME ESPECES", c'est ok pour le PNM. 

J'aime bien l'idée de @jolleon  qui propose de faire le lien entre les types de sites et les fichiers de formulaires à charger. On peut effectivement imaginer un dossier `custom_form` avec des modèles types (un par type de site), adaptable par un admin.

Ok pour merger les devs du volet SITE dans une nouvelle branche `dev_sites`.

**Comment by camillemonchicourt** [comment]
Les développements de la partie SITES ont été réalisés sur le fork https://github.com/jolleon/GeoNature-citizen/tree/mares
Ils sont en production sur https://www.a-vos-mares.org

Reste donc à les rendre plus générique et les intégrer dans ce dépôt.

**Comment by samuelpriou** [comment]
Bravo @lpofredc  pour ce travail !

**Comment by lpofredc** [comment]
Merci, tout le mérite revient à @jolleon et @QuentinJouet qui ont réalisé les développements de ce projet.

Au jour d'aujourd'hui, c'est un module "mares" avec le formulaire d'état des lieux détaillé inscrit "en dur" dans le code. Il devra évoluer vers un outil adaptatif permettant sur un programme d'inventorier différents types de sites avec des formulaires adaptés à chaque types de sites.

Il reste également un important  d'intégration de ces développements à GeoNature-citizen qui a évolué en parallèle à ce développement (dont une montée en version d'Angular v6 > v8).

**Comment by sig-pnrnm** [comment]
Question naive (alors soyez indulgents :wink: ) : 

Ce module "sites" (ou "mares", ou "arbres remarquables") pourrait répondre aux besoins de plusieurs collègues.

Nous n'avons pas d'instance GeoNature-Citizen, mais une instance GeoNature (v1 et prochainement v2).
Est-il possible (ou aurait-il été possible) d'intégrer ce module sites à GeoNature plutôt qu'à GeoNature-Citizen ?
Je vous propose plusieurs réponses : 
- oui, c'est tout à fait possible : ça pourrait être un module de GeoNature
- oui, mais c'est trop tard
- non, car ce n'est pas dans l'esprit de GeoNature : GeoNature vise des scientifiques et GeoNature-Citizen vise le grand-public
- non car ce ne sont pas du tout les mêmes technologies
- ...

**Comment by camillemonchicourt** [comment]
Le mode "Site" est totalement intégré dans GeoNature-citizen, qui est un outil à part et non pas un module de GeoNature. C'est même pas vraiment un module de GeoNature-citizen mais plutôt un mode de GeoNature-citizen. 

Et GeoNature-citizen est autonome et indépendant de GeoNature, même si il peut être intégré dans son écosystème, de la même manière que GeoNature-atlas. Voir https://github.com/PnX-SI/GeoNature-citizen/issues/100

Ce n'est pas du tout conçu ni développé comme un module GeoNature et c'est fait pour être accessible en ligne à tous, orienté grand public, avec authentification optionnelle si on veut saisir des données etc...

**Comment by camillemonchicourt** [comment]
Fichier de description des champs du programme "mares" : https://github.com/PnX-SI/GeoNature-citizen/blob/dev/config/custom/form/mares.json

**Comment by nobohan** [comment]
Bonjour, 

Nous allons utiliser Geonature-citizen dans un projet de relevés d'éléments de biodiversité dans une commune en Belgique. Je cherche à comprendre comment configurer un programme de type site. Le fichier mentionné ci-dessus (https://github.com/PnX-SI/GeoNature-citizen/blob/dev/config/custom/form/mares.json) serait bien utile mais le lien est mort. 

Pouvez-vous maj le lien?

merci d'avance

**Comment by camillemonchicourt** [comment]
@lpofredc et @samuelpriou, vous avez des exemples de configuration de programmes en mode "espèces" (avec champs additionnels) ou en mode "sites" à partager ?
Merci.

**Comment by camillemonchicourt** [comment]
Merci @samuelpriou, une documentation générale sur la configuration des champs additionnels des programmes était prévue, non ?

**Comment by samuelpriou** [comment]
Oui...
Je vais le faire.

**Comment by lpofredc** [comment]
Je viens de crééer un GIST avec quelques configs de la LPO AuRA:
https://gist.github.com/lpofredc/a85e994776efd6a63757d2817fd7862c

Vous pouvez utiliser ce site pour tester et développer vos propres configs.

En parallèle, je réfléchis à un moyen de partager toutes ces ressources (hub Citizen, voire GeoNature ?).

**Comment by lpofredc** [comment]
... le site de test... 
https://partage.lpo-aura.org/minisite/ajsf/
