### ISSUE TITLE
Erreur suite a install docker

### ISSUE THREAD

**Issue by Celedhrim** [PnX-SI/GeoNature-citizen#343]
Bonjour,

Suite a install docker de geocitizen j'ai cette erreur a la creation d'un user dans l'admin citizen : 

```
Integrity error. (psycopg2.errors.NotNullViolation) null value in column "password" of relation "t_users" violates not-null constraint DETAIL: Failing row contains (2, monpetituser, monpetituser, monpetituser, null, monpetituser@mondomaine, 0100000000, sdlkjfsmkldjqf, sdf, t, t, 2022-03-13 17:00:45.500691, 2022-03-13 17:00:45.500698). [SQL: INSERT INTO gnc_core.t_users (name, surname, username, password, email, phone, organism, avatar, active, admin, timestamp_create, timestamp_update) VALUES (%(name)s, %(surname)s, %(username)s, %(password)s, %(email)s, %(phone)s, %(organism)s, %(avatar)s, %(active)s, %(admin)s, %(timestamp_create)s, %(timestamp_update)s) RETURNING gnc_core.t_users.id_user] [parameters: {'name': 'monpetituser', 'surname': 'monpetituser', 'username': 'monpetituser', 'password': None, 'email': 'monpetituser@mondomaine', 'phone': '0100000000', 'organism': 'sdlkjfsmkldjqf', 'avatar': 'sdf', 'active': True, 'admin': True, 'timestamp_create': datetime.datetime(2022, 3, 13, 17, 0, 45, 500691), 'timestamp_update': datetime.datetime(2022, 3, 13, 17, 0, 45, 500698)}] (Background on this error at: https://sqlalche.me/e/14/gkpj) 
```

Visiblement la requete construite a la creation du user envoie "null" pour le mot de passe , mais le schema ne veux pas de valeur null.

Pourtant dans le formulaire , aucune mention d'un champ password.

Merci,

**Comment by lpofredc** [comment]
Bonjour @Celedhrim,

En effet, les utilisateurs doivent être créés par inscription depuis l'interface publique du site. Le backoffice ne sert qu'à administrer les utilisateurs existants. 

Je viens de faire un correctif pour retirer (au moins temporairement), la possibilité de création d'un utilisateur depuis ce backoffice. 

Cette possibilité pourra être intéressant à l'avenir, elle impliquera alors de compléter le backoffice utilisateurs de diverses options:
- Générer un mot de passe aléatoirement 
- Pouvoir saisir manuellement un mot de passe
- Envoyer au nouvel utilisateur un email pour lui demander de créer son mot de passe
