### ISSUE TITLE
Création de mot de passe impossible avec certains caractères spéciaux ?

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/GeoNature-citizen#345]
Bonjour, 

La ville du Havre nous remonte qu'il est impossible de créer un mot de passe avec des caractères spéciaux tels les "*" (astérisques). Le message : "les mots de passent diffèrent", alors que j'ai fait le test et que ceux-ci sont identiques. 

Plateforme : https://observation.lehavre.fr/fr/home (merci de pas spammer le nombre d'utilisateurs tests et donc de le faire en local dans l'idéal). 

Il pourrait être important de le préciser ou de changer les caractères acceptés ?

**Comment by xavyeah39** [comment]
Je confirme le soucis en version 1.0.0.

**Comment by xavyeah39** [comment]
Salut,
Je rencontre toujours le problème sur plusieurs instances en version 1.1.0.
Si le mot de passe contient des caractères spéciaux tels que `*` ou `\` le contrôle indique "Les mots de passe diffèrent" alors qu'ils sont bien identiques : 

![Image](https://github.com/user-attachments/assets/da8a63b9-d4f0-4c97-9ba2-797567013c2e)

**Comment by xavyeah39** [comment]
Hello, l'issue est fermée mais nous rencontrons toujours le problème en version 1.3.1
