### ISSUE TITLE
[Backend] Lru_cache empêche l'accès aux média récents des taxons

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature-citizen#347]
Bonjour,

J'ai l'impression que le `lru_cache` utilisé ici : https://github.com/PnX-SI/GeoNature-citizen/blob/27181ea767407bb70775bc8e71a0076f68e9631f/backend/gncitizen/utils/taxonomy.py#L80-L88
empêche l'actualisation des média de chaque taxon quand ils sont changés depuis Taxhub. Cela est visible notamment lorsqu'il faut renseigner le taxon observé lors d'une observation.

Il est nécessaire de redémarrer l'application pour apparemment invalider le cache et actualiser les médias.

Avez-vous observé les mêmes problèmes ?
Y a-t-il un moyen de limiter ce cache dans le temps ?

**Comment by lpofredc** [comment]
Système de chargement des listes taxonomiques entièrement revu. La mise à jour des données issues de taxhub  peut se faire directement depuis le backoffice sans redémarrer l'appli.
