### ISSUE TITLE
Envoi automatique d'emails

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature-citizen#353]
Bonjour tout le monde,

J'ai une petite question à propos de l'envoi automatique d'email lors de la demande de création de compte. J'ai renseigné le fichier `config.toml` comme il faut a priori, mais je ne trouve pas comment faire en sorte pour que cette nouvelle configuration soit prise en compte (j'ai renseigné ces informations après l'installation initiale il me semble). Y a-t-il une commande à exécuter ? Ou faut-il modifier directement le fichier `frontend/src/conf/app.config.ts` comme je l'ai fait pour changer le titre de l'application ?

Petite info supplémentaire : je suis prêt à participer à la mise à jour de la documentation de GeoNature-citizen en avril/mai (pendant que je suis dedans, car dans quelques mois, ce sera plus compliqué !). Mais je vais avoir besoin de quelqu'un qui connaît bien cette appli pour vérifier que je n'écrive pas n'importe quoi... ;)

**Comment by camillemonchicourt** [comment]
Salut, je ne connais pas le fonctionnement de GeoNature-citizen et ne l'utilise pas.
J'ai cherché ce sujet dans la doc mais pas trouvé.

Pour moi, les paramètres d'email ne sont que niveau backend, et pas frontend.

Je pense qu'il faut recharger ou redémarrer le backend de GeoNature-citizen pour prendre en compte les modifications du fichier `config.toml`.
Peut-être avec un `sudo -s supervisorctl reload geonature` comme indiqué ici : https://github.com/PnX-SI/GeoNature-citizen/blob/master/install/update_app.sh#L18 🤔

**Comment by mvergez** [comment]
Bonjour,

Oui normalement pour la configuration du mail, tout se passe en backend. Il faudrait alors redémarrer le service GeoNature Citizen pour que la configuration soit prise en compte : `sudo supervisorctl restart gncitizen_api`

Il faudrait absolument qu'on mette à jour la documentation effectivement... Et qu'on fasse un peu de ménage.
Ce serait trop cool comme contribution @geobrun, merci beaucoup !!!

N'hésite pas à commenter si ça ne fonctionne toujours pas

**Comment by geobrun** [comment]
Ok, merci pour vos conseils, cela fonctionne ! J'avais donc la bonne commande, il me manquait juste `gncitizen_api` à la fin.

Je vais voir pour mettre à jour la doc dans les semaines qui viennent.

**Comment by camillemonchicourt** [comment]
J'ai fait une petite PR, mentionnant la commande à exécuter pour appliquer les modifications de la conf : https://github.com/PnX-SI/GeoNature-citizen/pull/354

Je réouvre ce ticket car non terminé tant que ces évolutions de la doc ne sont pas répercutés dans une release.
