### ISSUE TITLE
Affichage des observations citizen dans geonature-atlas

### ISSUE THREAD

**Issue by spelhate** [PnX-SI/GeoNature-citizen#356]
Bonjour,
Je découvre Citizen et je connais un peu Géonature pour l'avoir déployé à la Région Bretagne.
Je souhaite savoir s'il est nativement possible d'afficher les observations saisies dans Citizen dans Géonature Atlas.

- Si oui : où s'effectue cette configuration ?
- Si non  : Quel serait le moyen le plus propre d'y arriver ?

**Comment by camillemonchicourt** [comment]
A noter que pour faciliter les interrogations entre GeoNature-citizen et GeoNature, il est possible que le schéma de BDD de GeoNature-citizen soit intégré directement dans la BDD de GeoNature.
Voir discussion récente sur le sujet dans un autre ticket.

**Comment by spelhate** [comment]
Merci pour toutes ces précisions @camillemonchicourt
Nous allons étudier de notre côté les différentes options et revenir vers vous pour discuter les pistes techniques.

**Comment by lpofredc** [comment]
Bonjour, Voici le script et la doc pour la mise en place d'une alimentation automatique de GeoNature depuis GeoNature-citizen: https://github.com/PnX-SI/GeoNature-citizen/tree/master/data/addons/scripts/gnc2gn_synthese

Je recommande d'analyser le SQL pour savoir si cela répond bien à vos besoins. Il peuple le GeoNature par trigger (nécessite en effet que citizen soit dans la même bdd que geonature) Par défaut, les données ont le statut de validation "en attente de validation" (cd_nomenclature = '0').

Les cadres d'acquisition sont créés à partir des projets, les jeux de données à partir des enquetes. Si vous avez déjà des cadres d'acquisition et/ou des jeux de données, vous pouvez utiliser leurs UUID pour créer les projets et enquêtes dans votre instance de Citizen.

**Comment by spelhate** [comment]
Merci @lpofredc
