### ISSUE TITLE
Impossible de valider une observation sur le formulaire AJOUTER UNE OBSERVATION

### ISSUE THREAD

**Issue by EtangNoir** [PnX-SI/GeoNature-citizen#360]
Bonjour, 

J'ai installé GeoNature citizen (1.0.0-dev sur un serveur Debian 11) en suivant les derniers gist : https://github.com/PnX-SI/GeoNature-citizen/issues/352. L'installation a l'air d'avoir bien fonctionné, j'ai pu créer des programmes reliés avec Taxhub; cependant, lorsque je veux valider une observation, le bouton "Valider l'observation" reste grisé. 

![Github_issue_citizen_2023](https://github.com/PnX-SI/GeoNature-citizen/assets/126081303/73717073-d941-4c93-8bfe-d29785f99bb9)

Je suis allé voir du coté : https://github.com/PnX-SI/GeoNature-citizen/blob/master/frontend/src/app/programs/observations/modalflow/steps/committed/committed.component.html 

 Valider l'observation
    </button>
    <button
        *ngIf="data.updateData"
        type="submit"
        **[disabled]="!form.obsForm.valid"** ## J'ai essayé d'enlever cette ligne pour voir mais ça ne marche pas non plus. 
        class="btn btn-default btn-big btn-outline-primary rounded-0"
        (click)="onUdpdateObs()"
        i18n="Upddate obs btn@@updateObsBtn"
    >

J'imagine que c'est un problème de formulaire. Pourriez-vous m'aiguillez s'il vous plait ?

Bonne journée.

**Comment by lpofredc** [comment]
Bonjour, c'est assez surprenant, le bloc de sélection d'espèce ne s'affiche pas. Sans taxon sélectionné, la validation est impossible. Pourriez-vous vous assurer que la liste d'espèce de taxhub n'est pas vide et redémarrer le back-end de geonature citizen?

**Comment by EtangNoir** [comment]
![Github_issue_citizen_2](https://github.com/PnX-SI/GeoNature-citizen/assets/126081303/2280fba0-f211-41be-b449-3c18bc549704)
J'ai simplement une espèce dans ma liste. 

J'ai redémarré via la commande :
```
 sudo supervisorctl restart gncitizen_api
``` 
A priori pas de changements, je ne sais pas si c'est bien la bonne commande ?

**Comment by camillemonchicourt** [comment]
OK je pense que c'est lié au fait qu'un mode "programme mono-espece" avait été prévu initialement mais n'est pas compatible avec le formulaire actuellement.
En effet on avait prévu que si le programme ne concernait qu'une seule espèce, alors il n'était pas utile de demander à l'utilisateur de la renseigner.
Mais le formulaire ne doit pas gérer ce cas qui a peut-être été peu testé ou oublié ?

**Comment by EtangNoir** [comment]
A priori, même avec plusieurs espèces, ça ne débloque pas la validation :
![Github_issue_citizen_3](https://github.com/PnX-SI/GeoNature-citizen/assets/126081303/1457c449-28ba-47d6-877f-802053cda8eb)

**Comment by lpofredc** [comment]
Le taxon dispose-t-il d'une photo dans taxhub? Il lui en faudrait une avec le type "Photo principale" puis redémarrer le back-end de citizen. Le composant de sélection d'espèce gère les listes mono espèces mais en affichant une image de l'espèce.

**Comment by EtangNoir** [comment]
Je viens d'ajouter une photo, elle apparait bien, mais on ne peut pas la sélectionner. Je ne sais pas si c'est normal ?
La saisie est bien dans l'emprise du programme oui. 

![Github_issue_citizen_4](https://github.com/PnX-SI/GeoNature-citizen/assets/126081303/f60ce1a8-b9c4-4fa7-bb18-f1e39a5c647c)

**Comment by mvergez** [comment]
Bonjour,

Petite question même si je pense avoir la réponse : avez-vous mis en place un formulaire personnalisé pour ce programme ? 
Il se pourrait qu'il s'affiche mal dans la fenêtre et donc vous empêche de valider le formulaire.

Y-a-t'il des erreurs dans la console javascript ? (clic droit, inspecter)

Merci

**Comment by EtangNoir** [comment]
Bonjour, 

Non, je n'ai pas associé mes programmes à un formulaire personnalisé.  Pour la console, il ne me semble pas avoir d'erreurs particulières : 

![Github_issue_citizen_5](https://github.com/PnX-SI/GeoNature-citizen/assets/126081303/50a62c4c-ff5d-4f32-9c95-4117f75e54b9)

![Github_issue_citizen_5 (2)](https://github.com/PnX-SI/GeoNature-citizen/assets/126081303/b9a72d70-b506-48c6-beb4-35afaf119357)

**Comment by lpofredc** [comment]
Voir si ce n'est pas lie a #261?

**Comment by camillemonchicourt** [comment]
Oui l'observation étant à l'ouest, ça me semble bien lié à #261.
Ce soucis semble corrigé dans un fork (https://github.com/pierre56/GeoNature-citizen/commit/20086e9a9b752825e6c53235e9e7b8efaf826fc6) mais pas répercuté dans le dépôt principal par une pull request ?

**Comment by EtangNoir** [comment]
Effectivement, j'ai suivi le https://github.com/PnX-SI/GeoNature-citizen/issues/261 et je peux maintenant valider le formulaire.
Merci beaucoup !!

J'ai une autre erreur cependant, lorsque la donnée est validée et que je me connecte à un compte sur le tableau de bord, le message suivant apparait "une erreur est survenue lors de la récupération des données sur le serveur" et la page affiche une icône de chargement. Dans la console, j'ai une erreur liée à "Http failure response" "404 NOT FOUND" en lien avec une récompense (api/rewards/4) ? Peut-être ouvrir un autre issue ?
