### ISSUE TITLE
Galerie photo

### ISSUE THREAD

**Issue by hypsug0** [PnX-SI/GeoNature-citizen#365]
Dans le cadre du passage du projet Un dragon dans mon Jardin sur GeoNature-citizen, la SHF a demandé l'ajout d'une galerie photo des observations d'un programme permettant l'exploration des observations par photo en complément de l'exploration cartographique habituelle.

Cette galerie photo a été intégrée à l'emplacement de la carte. Un bouton permet de switcher entre la carte et la galerie.

![Screenshot 2023-12-13 at 23-48-06 GeoNature-citizen - Un dragon dans mon jardin](https://github.com/PnX-SI/GeoNature-citizen/assets/42280769/c747f21d-3e02-47cc-b97b-a622f2180eb5)

![Screenshot 2023-12-13 at 23-48-39 GeoNature-citizen - Un dragon dans mon jardin](https://github.com/PnX-SI/GeoNature-citizen/assets/42280769/a81f4f90-3df6-432a-98bc-a98a73b7b20d)

**Comment by camillemonchicourt** [comment]
OK pourquoi pas, même si je trouve ça peut classique ni intuitif dans une logique Carte-Liste, mais je vois pas non plus trop comment j'aurai donné accès à la galerie des photos.
Peut-être à rendre désactivable car c'est une fonctionnalité que je trouve un peu spéciale ?

**Comment by camillemonchicourt** [comment]
Intégré dans la version 1.0.0.
Non désactivable à priori.
