### ISSUE TITLE
[BUG] - Envois d'email lors de la création de compte

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/GeoNature-citizen#395]
### What is the bug or the crash?

L'email envoyé lors de la création d'un compte ne fonctionne pas car il ne trouve pas les valeurs attribuées aux variables {app_url} et {app_name} tel qu'attendu dans le template de l'email défini ici : https://github.com/PnX-SI/GeoNature-citizen/blob/a8a23bc4bc44174921249672cf56b4f62aa6d7c2/config/config.toml.template#L52

Sauf erreur, il faudrait modifier la ligne suivante https://github.com/PnX-SI/GeoNature-citizen/blob/a8a23bc4bc44174921249672cf56b4f62aa6d7c2/backend/gncitizen/utils/mail_check.py#L94
par :
```
html_message=template.format(
    activate_url=activate_url,
    app_url=current_app.config["URL_APPLICATION"],
    app_name=current_app.config["appName"],
),
```

### Steps to reproduce the issue

Pour reproduire le problème, il faut créer un compte sur une instance GnCitizen.
L'erreur est visible dans le fichier de logs ~/gncitizen/var/log/gunicorn_gncitizen_errors.log 

exemple : 
```
WARNING in mail_check: send confirm_email failled. 'app_url'
```

### Versions

1.0.0

### Additional context

-

**Comment by camillemonchicourt** [comment]
Si tu as testé ta proposition et qu'elle fonctionne, n'hésite pas à proposer une pull request pour corriger ce soucis.

**Comment by lpofredc** [comment]
Corrigé dans la v1.1.0
