### ISSUE TITLE
Paramètre NEW_OBS_POINTER - module sites

### ISSUE THREAD

**Issue by MNourrisson** [PnX-SI/GeoNature-citizen#397]
### What is the bug or the crash?

Bonjour,

j'ai personnalisé l'icône du paramètre NEW_OBS_POINTER présent dans 
https://github.com/PnX-SI/GeoNature-citizen/blob/a8a23bc4bc44174921249672cf56b4f62aa6d7c2/frontend/src/conf/map.config.ts.template#L80
mais l'icône ne change pas quand on utilise le module "sites".
(J'ai également personnalisé OBS_POINTER et cette icône est bien modifiée.)

### Steps to reproduce the issue

Capture dans le module observations 
![observations](https://github.com/PnX-SI/GeoNature-citizen/assets/34370970/c746e6c6-0a86-4601-8ec4-7b47ea5ee13a)

Capture dans le module sites
![sites](https://github.com/PnX-SI/GeoNature-citizen/assets/34370970/6e2a2390-b145-412a-9ead-6d41d3ef1835)

### Versions

1.0.0

**Comment by hypsug0** [comment]
En effet, le pointeur est écrit en dur. 

https://github.com/PnX-SI/GeoNature-citizen/blob/a8a23bc4bc44174921249672cf56b4f62aa6d7c2/frontend/src/app/programs/sites/siteform/siteform.component.ts#L37

Je vois pour corriger ça rapidement.

**Comment by lpofredc** [comment]
Corrigé dans la v1.1.0
