### ISSUE TITLE
Formatage date

### ISSUE THREAD

**Issue by MNourrisson** [PnX-SI/GeoNature-citizen#398]
### What is the bug or the crash?

Bonjour,

dans la vue détaillée d'un site, une des dates n'a pas le même format que les autres.
Cela ne se produit pas dans la vue détaillée d'une observation.

### Steps to reproduce the issue

Module observations :
![observations](https://github.com/PnX-SI/GeoNature-citizen/assets/34370970/c549992e-d4a2-4902-a7fc-3f830201664a)

Module sites : 
![sites](https://github.com/PnX-SI/GeoNature-citizen/assets/34370970/7eb5a86b-150c-41d1-857d-0bab46913e2e)

### Versions

1.0.0

**Comment by lpofredc** [comment]
Corrigé dans la v1.1.0
