### ISSUE TITLE
[NS] Saisie d'une observation: cas des observateurs non enregistrés

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#47]
Pour l'utilisateur non connecté, on lui propose (champ non obligatoire) de saisir son nom. Si l'utilisateur est enregistré, le champ est caché.

**Comment by patkap** [comment]
L'intention de rester anonyme ou de contribuer publiquement est déterminée en amont de la présentation du formulaire.
![image](https://user-images.githubusercontent.com/11497003/53489208-e13bb900-3a90-11e9-8f40-354612ae7006.png)

**Comment by patkap** [comment]
Après concertation, la proposition est d'intégrer un champs d'identification/contact optionnel dans le formulaire d'enregistrement d'observation.

**Comment by camillemonchicourt** [comment]
Oui, merci.
Même en non authentifié, il faut que la personne puisse renseigner (optionnellement) son nom et contact.

**Comment by orovellotti** [comment]
Ca me semble pas nécessaire pour cette version. 

L'utilisateur créer un compte si il veut renseigner son nom et contact ?

**Comment by lpofredc** [comment]
> Même en non authentifié, il faut que la personne puisse renseigner (optionnellement) son nom et contact.

Non compatible RGPD...

**Comment by camillemonchicourt** [comment]
Dommage, pour moi libre à chacun de le remplir ou pas.
On pourrait même prévoir un paramètre pour que chaque instance choisisse de les afficher ou les masquer.
A garder en évolution je pense car ça faisait partie du fonctionnement initial souhaité

**Comment by jbdesbas** [comment]
> > Même en non authentifié, il faut que la personne puisse renseigner (optionnellement) son nom et contact.
> 
> Non compatible RGPD...

Même en ajoutant une checkbox de consentement libre, éclairé, etc.. ? Ca risque juste d'être un peu chiant si la personne exerce son droit d'accès/suppression car il faut alors chercher son nom en chaîne de caractère (mais ca ne va pas arriver tous les jours)

**Comment by camillemonchicourt** [comment]
Je m’embarrasserait pas avec une checkbox.
Ils vaudrait mieux un paramètre pour ne pas afficher ces champs optionnels pour ceux qui aiment le RGPD. :-)

**Comment by jbdesbas** [comment]
Je pense (à 80%) que c'est possible d'avoir ces champs tout en étant RGPD-friendly ;-) Sinon la checkbox peut juste permettre de dégriser les champs optionnels (rien à gérer côté backend du coup).
