### ISSUE TITLE
[NS] Saisie d'une observation: Seuil de zoom minimum pour une saisie

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#49]
Pour assurer un minimum de précision aux saisies, il faut imposer un seuil mini de zoom pour localiser une observation. Cela doit être configurable dans le fichier de conf de la carte, une valeur par défaut de 14 semble adaptée.

**Comment by patkap** [comment]
Par défaut, la carte du formulaire est centrée et ajustée sur l'aire du programme. 
L'observateur est libre de zoomer dans les 2 sens et de se déplacer pour se repérer.
L'enregistrement des coordonnées de l'observation est contrainte (presque) à l'aire du programme.

**Comment by orovellotti** [comment]
Attention les niveaux de zoom max ne sont pas homogènes pour les different providers (GMap, OSM,IGN)
Difficile d'imposser le niveaux 14 qui n'est disponible que sous OSM.

**Comment by camillemonchicourt** [comment]
Ce n'est pas vraiment le sujet. 
Chacun aura la gestion de son GeoNature-citizen, utilisera les fonds qu'il souhaite et pourra définir (ou pas)  un niveau de zoom minimum pour la saisie.

**Comment by samuelpriou** [comment]
Effectivement chaque structure pourra choisir d'utiliser un fond plutôt qu'un autre avec un seuil de zoom minimal.

**Comment by lpofredc** [comment]
Ok, merci @patkap, c'est en partie implanté. Revoir le message qui n'est pas explicite à part pour un développeur web habitué des librairies carto. Je propose:

 `Veuillez zoomez pour localiser votre observation`

Testé sur les autre possibilités de localiser l'observation: 
* Sur la carte/liste du programme, pas d'effets du seuil.
* Sur la carte de saisie en plein écran, pas possible de pointer si l(on a pas atteint le seuil mais aucun message d'alerte, on croit à un bug. 

![Capture d’écran - 2019-04-23 à 10 19 31](https://user-images.githubusercontent.com/22891423/56565805-7949b080-65b1-11e9-872d-2fe5b85129c5.png)

**Comment by orovellotti** [comment]
Bonjour à tous

On a fait un test ergo avec Patrick.

Il me semble qu'il serait plus pertinent de laisser l'utilisateur faire une saisie quelque soit le niveau de zoom et le laisser ajuster ensuite en deplacent le curseur.

1/ Je clicke, 2/ j'ajoute, 3/ je zoome, 4/ je deplace le curseur.

On peut ajouter un label au dessus de la carte pour signifier à l'utilisateur le fait qu'il devrait zoomer pour etre plus precis.

Sinon le label va etre au dessus de toutes les cartes, meme en plein ecrant et ca risque de frustrer énnormement l'utilisateur.

Merci
