### ISSUE TITLE
[NS] Page observateur: RGPD

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#52]
Deux boutons gestion rgpd:

- Supprimer le compte (anonymise automatiquement toutes les données attributaires en mettant NULL dans le champ de clé étrangère vers la table des utilisateurs > DELETE sur /api/user/delete
- Exporter ses données personnelles (nom d'utilisateur, email, etc.) > GET sur /api/user/info

**Comment by patkap** [comment]
Il serait intéressant de produire une petite doc, pour les observateurs comme pour les devs que l'on embarque, sur la gestion des informations personnelles au sein des apps front et back.
