### ISSUE TITLE
[NS] Mise en place d'Angular Universal et optimisation SEO

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#53]
Mise en place d'Angular en mode Server-side rendering et d'un système de lancement du service côté serveur (à l'image de gunicorn/supervisor pour le backend).

**Comment by patkap** [comment]
digitalocean propose un [tutoriel](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-18-04) en s'appuyant sur [PM2](https://pm2.io/doc/en/runtime/overview/). L'un d'entre vous l'a-t'il déjà mis en oeuvre ?

**Comment by lpofredc** [comment]
J'ai vu ça hier. Pour le moment, j'ai créé un service avec systemd selon ce tuto [Run node.js service with systemd](https://www.axlleqnt.org/docs/view/nodejs-service-with-systemd/)

**Comment by lpofredc** [comment]
suite à #120
