### ISSUE TITLE
[NS] Page programme : Filtrage des données

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#58]
Mettre en place le filtrage des données dans le bloc liste/carte. Deux options, selon moi la première à privilégier:

1. Tout géré côté frontend, de mon point de vue le plus efficace et le plus efficace (sans si gros jeu de données). 
2. Filtrage côté backend via API.

**Comment by patkap** [comment]
On veut pouvoir filtrer (ou ordonner?) par taxon et par commune (possédant une intersection géographique avec l'aire du programme).

**Comment by lpofredc** [comment]
Filtrage côté frontend
