### ISSUE TITLE
Saisie d'une observation, jointure avec les communes

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#59]
Peupler le champ  ``municipality`` de la table des observations.

Créer une fonction générique permettant de retrouver l'``id_area`` de la ``municipality`` à partir d'une localisation côté backend.

Créer une fonction générique permettant de retrouver une commune (et son code insee ?) à partir de son ``id_area``. à l'image de celle utilisée pour retrouver l'espèce d'après le ``cd_nom`` taxref.

**Comment by orovellotti** [comment]
C'est un gros chantier:

1/ Créer la fonction générique qui récupère la municipalité a partir d'un point
2/ Mettre en place un trigger en écriture sur ajout d'une observation
3/ Mettre a jour les routes coté Backend
4/ Adapter le front

**Comment by camillemonchicourt** [comment]
Mais non, c'est juste un trigger intersect et la fonction générique existe déjà dans GeoNature.

**Comment by orovellotti** [comment]
Donc c'est juste écrire le trigger qui utilise la fonction générique pour ajouter la "municipality" en base sans faire de modif front ?

**Comment by lpofredc** [comment]
Oui, 3 possibilités:
Géré directement en bdd avec un trigger (comme dans geonature) > Complexifie le processus d'installation avec la nécessité d'éxécution d'un sql pas encore nécessaire) mais simple à mettre en oeuvre.
Géré côté backend au moment de l'enregistrement de la donnée d'après la géométrie saisie. 

Personnellement, j'aurai tendance à privilégier la seconde solution en ajoutant également `flask-migrate` aux modules du backend, permettant une gestion des évolutions des models par le backend (à la django).

**Comment by orovellotti** [comment]
@camillemonchicourt 
Est ce que tu peux nous donner plus d'info sur comment récupérer tout ca de geonature ? Merci

**Comment by lpofredc** [comment]
Ajouté dans cette PR #91

**Comment by lpofredc** [comment]
Le champ municipality du geojson des observations d'un programme contient maintenant deux informations sur la commune: 
* `name` > son nom
* `code` > son code insee 

```json
{
  "type": "FeatureCollection",
  "features": [{
    "properties": {
      "comment": "",
      "image": null,
      "timestamp_create": "2019-04-09 22:15:38.962272",
      "obs_txt": "Anonyme",
      "count": 1,
      "date": "2019-04-09",
      "common_name": "Merle noir",
      "id_observation": 185,
      "cd_nom": 4117,
      "sci_name": "Turdus merula",
      "municipality": {
        "code": "38185",
        "name": "Grenoble"
      }
    },
    "type": "Feature",
      "geometry": {
        "coordinates": [
          5.73486328125,
          45.16751538623502
        ],
      "type": "Point"
      }
      ...
```
