### ISSUE TITLE
Maquettes du Frontend

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-citizen#6]
Premières propositions à ajuster : 

![gnc-02](https://user-images.githubusercontent.com/4418840/47068160-d7a16b00-d1eb-11e8-86b1-40c5bda54c6b.jpg)

![gnc-01](https://user-images.githubusercontent.com/4418840/47068167-dc661f00-d1eb-11e8-98c9-123ca08b97a2.jpg)

![gnc-03](https://user-images.githubusercontent.com/4418840/47068175-e25c0000-d1eb-11e8-8bf2-ddaf778a5165.jpg)

![gnc-04](https://user-images.githubusercontent.com/4418840/47068185-e720b400-d1eb-11e8-9584-35c51f4445b0.jpg)

![gnc-05](https://user-images.githubusercontent.com/4418840/47068232-015a9200-d1ec-11e8-842d-d2df366bafa2.jpg)

![gnc-06](https://user-images.githubusercontent.com/4418840/47068198-f142b280-d1eb-11e8-976a-96f5dd431314.jpg)

![gnc-07](https://user-images.githubusercontent.com/4418840/47068217-f99aed80-d1eb-11e8-898b-503576945de4.jpg)

**Comment by lpofredc** [comment]
Magnifique! Faudra réfléchir pour les badges, en l'état, c'est très orienté montagne et méditerranée avec les vignettes :) et aussi à la possibilité d'intégration d'autres d'inventaires.

**Comment by camillemonchicourt** [comment]
Oui bien sûr. Là c'est une première base et de toute façon chacun pourra se créer ses propres badges comme il le souhaite.

**Comment by camillemonchicourt** [comment]
En effet je m'étais fait la même remarque.

**Comment by gildeluermoz** [comment]
Et comme chacun n'a pas la même hiérarchie de valeur pour les animaux, la hiérarchie des badges n'est pas parlante.

**Comment by samuelpriou** [comment]
Sinon ça peut être quelque chose comme ça :
premier niveau = 1 fleur ou 1 papillon ou 1 oiseau,
second niveau = 2 fleurs ou 2 papillons ou 2 oiseaux ,
etc...
Perso ça ne me dérange pas cette hiérarchie mais il serait souhaitable de rendre ce mode de représentation paramétrable pour chaque structure.

**Comment by orovellotti** [comment]
![1 login](https://user-images.githubusercontent.com/1989428/48256092-e22bda80-e40e-11e8-92ff-eb7fd3d1ebbd.png)
![2 programme](https://user-images.githubusercontent.com/1989428/48256093-e22bda80-e40e-11e8-9181-98ba162b481a.png)
![3 carte et obs](https://user-images.githubusercontent.com/1989428/48256094-e22bda80-e40e-11e8-81fe-b3e0d5c32464.png)
![4 nouvelle observation](https://user-images.githubusercontent.com/1989428/48256095-e22bda80-e40e-11e8-9447-894faef37bba.png)

Voila le wireframe modifié suite à notre réunion

**Comment by camillemonchicourt** [comment]
OK merci.

Par contre, je pense pas qu'il faille commencer par demander si on est Invité ou si on veut se logger. 

Il faut arriver sur la page d'accueil, avec la liste des programmes, pouvoir consulter chaque programme, en afficher le contenu, les observations etc...
Et c'est qu'au moment où on veut créer une Observation qu'il faut proposer de se logger. 

Attention cependant, cela va dépendre de comment est configurée l'instance de GN-citizen.
Il y a 3 cas : 
- Pas d'authentification
- Authentification obligatoire pour contribuer
- Mode mixte (authentification optionnelle)

Par ailleurs, quand on accède à un programme, il faut commencer par en afficher le contenu (Carte-Liste des observations filtrable).

Autre interrogation. Je suis pas convaincu qu'il faille découper la saisie en plusieurs étapes. Je l'aurai faite en une seule page car personnellement, avec les étapes, je ne sais pas directement en quoi consiste la saisie et ça me donne pas envie d'aller au bout.

**Comment by samuelpriou** [comment]
Je partage l'avis de Camille. Il faut que l'utilisateur rentre sur l'application et c'est effectivement au moment de saisir une observation qu'on lui propose de se logger, en gardant à l'esprit qu'il y a 3 possibilités : 

- Pas d'authentification
- Authentification obligatoire pour contribuer
- Mode mixte (authentification optionnelle)

Je pense également qu'il est préférable de ne pas découper la saisie par étapes.
Merci pour ces wireframes

**Comment by orovellotti** [comment]
En fait il n'y a deux étapes Saisie et Bravo/Badge.

Je vais revoir l'UX pour le login ...

Merci

**Comment by orovellotti** [comment]
Voila une nouvelle proposition

![hp](https://user-images.githubusercontent.com/1989428/48404935-a1df9b80-e731-11e8-883d-bcb9a316c96a.png)
![liste obs](https://user-images.githubusercontent.com/1989428/48404942-a73ce600-e731-11e8-85db-dd669e249989.png)
![nouvelle obs](https://user-images.githubusercontent.com/1989428/48404958-aa37d680-e731-11e8-8876-d24c6794a66e.png)
![badges et leader board](https://user-images.githubusercontent.com/1989428/48404964-ac019a00-e731-11e8-9d89-88772bb01a42.png)

**Comment by camillemonchicourt** [comment]
Ça me semble OK. 
A noter que : 
- Si il n'y a qu'un programme, on n'a pas l'étape "Choix du programme"
- Dans le cadre d'une instance mixte avec authentification optionnelle, il faut réfléchir comment proposer à l'utilisateur de se connecter, sans l'imposer.

**Comment by samuelpriou** [comment]
Oui cela représente bien les différentes étapes. 
Dans l'étape 1, il faut que les utilisateurs puissent voir les observations naturalistes des autres contributeurs et cela avant de s'identifier. Comme présenté ici : [https://user-images.githubusercontent.com/4418840/47068175-e25c0000-d1eb-11e8-8bf2-ddaf778a5165.jpg](url)

**Comment by camillemonchicourt** [comment]
Oui c'est ce qui est représenté par la première image de l'étape 2 : la visualisation de toutes les observations déjà existantes dans le programme.

**Comment by orovellotti** [comment]
Vous voulez que je rajoute une carto sur la page d'accueil?

**Comment by samuelpriou** [comment]
Oui il serait bien de visualiser rapidement les obs en cours. Un scroll et la carte apparait. On pourrait s'inspirer de [http://biodiversite.mercantour-parcnational.fr/](url)

**Comment by orovellotti** [comment]
Voila la toute dernière version 
![hp](https://user-images.githubusercontent.com/1989428/48411133-ede60c80-e740-11e8-9f88-4312882c48ab.png)
![liste obs](https://user-images.githubusercontent.com/1989428/48411134-ee7ea300-e740-11e8-8a3e-0cdcb0e3b347.png)
![nouvelle obs](https://user-images.githubusercontent.com/1989428/48411135-ee7ea300-e740-11e8-96b6-902b65928965.png)
![badges et leader board](https://user-images.githubusercontent.com/1989428/48411132-ed4d7600-e740-11e8-97aa-abbf1ea2c071.png)

Est ce que vous pouvez valdier ?

**Comment by samuelpriou** [comment]
Ok pour nous à la modération près que la consultation des badges ne doit pas être automatique après chaque saisie.
La consultation des niveaux de badges doit nécessiter une action de l'utilisateur pour aller les consulter. J'imagine quelque chose comme cliquer sur son compte et ainsi accéder à ce leader board.

**Comment by camillemonchicourt** [comment]
Le popup de login n'est affiché que dans le cas où on veut ou si il faut s'authentifier.

Oui le mode mixte permet à l'utilisateur de choisir si il s'authentifie ou pas pour saisir une observation mais dans ce cas c'est optionnel.

**Comment by samuelpriou** [comment]
Effectivement le mode mixte permet de laisser le choix à l'utilisateur de s'authentifier ou non.
La structure qui déploie GeoNature Citizen choisira un de ces 3 modes d'authentification : 
 
- Pas d'authentification
- Authentification obligatoire pour contribuer
- Mode mixte (authentification optionnelle).

Merci !

**Comment by Design-NS** [comment]
Est-il possible de savoir les liens que vous souhaitez mettre dans le footer du site ?
Merci !

**Comment by samuelpriou** [comment]
Voici ce qui me vient à l'idée :

- http://biodiversite.mercantour-parcnational.fr/
- http://www.mercantour-parcnational.fr/fr/des-actions/connaitre-et-proteger/les-atlas-de-la-biodiversite-communale-abc
- http://www.mercantour-parcnational.fr/fr/des-actions/connaitre-et-proteger/linventaire-biologique-generalise

**Comment by camillemonchicourt** [comment]
Sachant que cela doit être mis en place de manière générique. 
Chacun aura un contenu de Footer différent, voire pas de footer. 
Donc comme d'autres parties du frontend et comme sur GeoNature-atlas, il faudra qu'il soit désactivable (https://github.com/PnEcrins/GeoNature-atlas/blob/master/main/configuration/config.py.sample#L88-L89) et surcouchable (https://github.com/PnEcrins/GeoNature-atlas/blob/master/static/custom/templates/footer.html.sample).

**Comment by samuelpriou** [comment]
Effectivement il est préférable que le footer puisse être désactivable ou surcouchable et pensé de manière générique.

**Comment by gildeluermoz** [comment]
Magnifique. J'aime vraiment le design et l'ergonomie générale. 
Je n'aime pas le classement des observateurs par rang, 1er, 2ème, 3ème... C'est scolaire, infantilisant et décourageant pour les derniers. C'est le principe de l'école à la française : en voulant encourager l'élite on décourage ceux qui n'y sont pas. 



		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0) 4 92 40 20 38 (lundi) 
+33 (0)4 92 21 08 49 (mardi, mercredi matin et jeudi) 
[ http://www.ecrins-parcnational.fr/ | www.ecrins-parcnational.fr ] 

[ http://actu.ecrins.info/ ] 


De: "Design-NS" <notifications@github.com> 
À: "PnX-SI" <GeoNature-citizen@noreply.github.com> 
Cc: "Gil DELUERMOZ" <gil.deluermoz@ecrins-parcnational.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Jeudi 6 Décembre 2018 10:26:27 
Objet: Re: [PnX-SI/GeoNature-citizen] Maquettes du Frontend (#6) 



Bonjour tout le monde, 
Voici les nouvelles maquettes pour Geonature Citizen 
[ https://user-images.githubusercontent.com/45397017/49574639-3019fc80-f941-11e8-8117-5efd7803ff8e.png ] 
[ https://user-images.githubusercontent.com/45397017/49574651-35774700-f941-11e8-9efe-ef5a245b1415.png ] 
[ https://user-images.githubusercontent.com/45397017/49574659-390ace00-f941-11e8-810c-9eb95bdb0234.png ] 
[ https://user-images.githubusercontent.com/45397017/49574670-3c05be80-f941-11e8-9654-831ec358b490.png ] 
[ https://user-images.githubusercontent.com/45397017/49574681-3f994580-f941-11e8-9c63-21dfcbe749d0.png ] 
[ https://user-images.githubusercontent.com/45397017/49574722-5475d900-f941-11e8-98c0-216445623000.png ] 
[ https://user-images.githubusercontent.com/45397017/49574731-5770c980-f941-11e8-966b-687b22de10fe.png ]

**Comment by Design-NS** [comment]
@gildeluermoz merci pour ces commentaires !
Lors de notre précédente réunion téléphonique, nous avions établis avec @samuelpriou ces différents badges, et justement la question des badges cuivre, argent et or (en plus de tous les autres.)

**Comment by TheoLechemia** [comment]
Je rejoins Gil c'est vraiment classe !
Et aussi d'accord sur le classement. Les badges (novices/confirmé/expert) peuvent suffire, le classement est pas forcément nécessaire. D'ailleurs les logos de ces badges (loupe/jumelle/caméscope) sont beaucoup plus parlant qu'avant !

**Comment by samuelpriou** [comment]
Bonjour,

Merci pour ces maquettes qui donnent envie de se mettre à la saisie.
Je partage l'avis de @gildeluermoz "_Magnifique. J'aime vraiment le design et l'ergonomie générale_"
En ce qui me concerne, je ne suis pas contre un classement. Même si je ne suis pas dans les premiers, je ne pense pas qu'un classement incite à renoncer. A discuter tous ensemble toute à l'heure.

**Comment by orovellotti** [comment]
Bonjour a tous 

Etant donnée la complexité du projet et le budget restrain nous ne pouvons pas nous engager à rendre la page d'accueil administrable.

C'est un template administrable par un developpeur (ie: ce n'est pas un CMS)

Merci

**Comment by DonovanMaillard** [comment]
Bonjour, superbe en effet! 

Idem pour le classement, les badges me semblent suffisants . 

Dommage pour le coté "administrable", mais quelle difficulté ca représente actuellement? Est-ce plus difficilement administrable que l'atlas par exemple? Quel surcout pour quelque chose d'administrable plus simplement?

**Comment by samuelpriou** [comment]
En ce qui concerne les badges et afin de valoriser les contributions je me disais qu'il serait peut être intéressant de n'afficher que les badges déjà déclenchés. Cela suppose donc de ne pas voir en transparence les badges à venir. Cela aura pour conséquence une forme de valorisation inattendue qui surprend. Les badges seront ainsi décernés de manière non linéaire et cela pourrait renforcer la participation des contributeurs...

**Comment by orovellotti** [comment]
Pour les rangs, le leaderboard est extrêmes efficace pour les premiers qui veulent absolument rester dans les premiers (notamment les killers)

@gildeluermoz tu n'es pas un killer.

http://www.natural-solutions.eu/blog/gamification

**Comment by camillemonchicourt** [comment]
Salut à tous,

Pour clarifier quelques points et apporter des précisions/remarques : 
- La question des badges et le fonctionnement des badges a été définie dans la prestation initiale et affinée depuis par le prestataire et le commanditaire
- Il a été notamment souhaitée que les règles associées aux badges soient gérées dans la BDD ou avec des paramètres pour que chacun puisse les adapter à son contexte
- La gamification, avec les badges etc... a été souhaitée optionnelle. Ainsi elle ne sera pas forcément activée sur chaque instance de GeoNature-citizen pour ceux à qui ça ne parle pas, ou pour les programmes qui ne s'y prêtent pas. Au PNE par exemple, pour nos programmes participatives sur les bouquetins marqués et le lagopède je n'ai pas du tout prévu de l'activer. 
- Chaque structure déployant un GeoNature-citizen pourra ajouter ou modifier les badges mais cela sera à chacun de se débrouiller pour cela
- La page d'accueil sera paramétrable comme GeoNature-atlas, c'est-à-dire par un administrateur dans des fichiers de configuration, du CSS et des templates surcouchables
- Concernant les maquettes, c'est joli visuellement mais c'est à affiner car il y a plusieurs cas. Si il n'y a qu'un programme dans l'instance GeoNature-citizen alors on arrive directement sur la page du programme avec sa description (absente des maquettes ?) et la carte-liste des observations présentes dans le programme (il ne faut pas limiter aux 7 derniers jours car sinon ça sera vide, du moins il faut pouvoir proposer la carte-liste de toutes les observations avec des filtres. La plupart du temps ce sera des petits programmes comme des ABC avec très très peu de données). Si il y a plusieurs programmes alors sur la page d'accueil, on affiche tous les programmes et l'utilisateur commence par choisir son programme
- De la même manière, il y a des programmes de différents types (juste une espèce, quelques espèces ou beaucoup d'espèces). Selon le cas du programme parmi ces 3, le formulaire d'observation sera différent. Il faudrait aussi pouvoir accéder à de l'info sur chaque espèce provenant de TaxHub (photo bien sur mais aussi des infos de présentation de l'espèce, comment la reconnaitre... avec une approche générique et paramétrable)
- Je ne suis pas sur que le bloc "Les espèces observées en ce moment" soit vraiment fonctionnel au vu du faible nombre de données qu'il y aura la plupart dans chaque programme. Et ce bloc devra être masqué dans le cadre de programmes concernant une seule espèce.
- Il faut donc bien garder qu'un aspect essentiel est de pouvoir s'adapter aux différents contextes d'utilisation. Donc se concentrer sur les choses simples mais adaptables

> Il y un bloc dont je ne saisie pas bien le fonctionnement
> A quoi servent le volet déroulant et le recherche ? --> à trouver plus facilement une espèce pour la saisie ?

A mon avis, il y a là un mélange entre 2 types de programme : ceux qui n'ont que quelques taxons et que l'on affiche sous forme de petit mur de photo et les programmes où on a beaucoup de taxons pour lesquels il faut pouvoir rechercher le taxon dans une liste. Mais ça devrait être l'un ou l'autre.

**Comment by DonovanMaillard** [comment]
Merci pour toutes ces précisions :) 👍

**Comment by orovellotti** [comment]
Ok pour résumé cette histoire de "Saisie d'une obs", trois options:

- Programme mono espèce : On affiche l'espèce sur l'écran de saisie
- Programme jusqu'à 10 espèces : On affiche les 10 espcèces en vignette
- Programme à plus de 10 espèces : On affiche les deux listes déroulantes (Groupe INPN, et nom du taxon) avec autocompletion et on voie la vignette de l'espèce

@Design-NS OK ?

**Comment by camillemonchicourt** [comment]
Exact, le seuil de 10 devant être par défaut mais paramétrable

**Comment by orovellotti** [comment]
@Design-NS @samuelpriou c'est effectivment intéressant de ne pas afficher du tout les badges pour créer l'effet de surprise (Grisé en premier).

**Comment by camillemonchicourt** [comment]
Démo de la maquette en ligne - https://github.com/PnX-SI/GeoNature-citizen/issues/5

**Comment by lpofredc** [comment]
Projet de maquette abouti
