### ISSUE TITLE
[NS] Affichage des images espèces et programmes

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#61]
Tout la biodiversité n'est pas azuré :) 

Mettre en place l'affichage des vignettes des espèces sur la carte/liste et dans le formulaire espèce avec les médias taxhub (médias tests disponibles via les scripts de @amandine-sahl sur TaxHub (https://github.com/PnX-SI/TaxHub/tree/master/data/scripts).

Reste à décider de la manière de gérer les médias chargés par les observateurs:
- Affichés en remplacement de la vignette? (je doute de la qualité du rendu à cette taille)
- Afficher sur un modal détaillant l'observations plus grand que celui actuel (cf. ci-dessous)?
- Afficher une galerie des photos postées par les observateurs (sous la carte/liste?)
- Autre propositions?

![capture d ecran - 2019-03-04 a 23 41 07](https://user-images.githubusercontent.com/22891423/53767813-359ec880-3ed7-11e9-9740-e13189463e4a.png)

**Comment by lpofredc** [comment]
idem pour l'affichage des pictos des programmes

**Comment by orovellotti** [comment]
Pour l'observation concerné on garde l'image de l'observateur

**Comment by orovellotti** [comment]
Attention: Si les deux applications sont distantes il risque d'avoir des problèmes de latences a l'affichage

**Comment by patkap** [comment]
fusionner avec #82

**Comment by lpofredc** [comment]
Touche finale dans la PR #140.
