### ISSUE TITLE
Utilisateur: Fonction "Reset Password" à mettre en place

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#63]
Mettre en place un dispositif de récupération de mot de passe perdu (envoie par email d'une clé unique et vérification d'authenticité avec cette clé pour permettre la restauration?).

Des pistes possibles:
- https://stackoverflow.com/questions/48983616/reset-the-password-in-flask-python
- https://gist.github.com/josephturnerjr/9672884

**Comment by orovellotti** [comment]
Il faudrait : 
1/ Mettre en place un Serveur SMTP
2/ Coder le formuliare "jai perdu mon mot de passe"
3/ Coder la fonctionalité envoie de Reset
4/ Coder la formulaire "Reset password"
5/ Check pour deux password indentiques

**Comment by lpofredc** [comment]
Au jour d'aujourd'hui, ce qui a été fait par @patkap : 

1. Mettre en place un Serveur SMTP > Pas nécessaire, on utilise la lib python native [smtplib](https://docs.python.org/3/library/smtplib.html)
2. Coder le formuliare "jai perdu mon mot de passe" > Fait, demande nom d'utilisateur et mot de passe (réduire à mot de passe?)
3. Coder la fonctionalité envoie de Reset > Envoie un nouveau mot de passe par email.
4. Coder la formulaire "Reset password" > Pas implanté
5. Check pour deux password indentiques > Pas implanté

**Comment by camillemonchicourt** [comment]
La réinitialisation du mot de passe semble corrigée et fonctionnelle depuis.
