### ISSUE TITLE
Interface BackOffice d'administration des programmes

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#65]
Il faudrait prévoir un BackOffice d'édition du texte des programmes en HTML (Pour plus tard )

**Comment by lpofredc** [comment]
Ajout d'une fonctionnalité d'édition des géométries > 380460e6c6e8a50eb255a094d8aaafae2d6b8dad

*ATTENTION,* nécessite un compte MapBox poiur afficher les fonds de cartes (prévoir une PR sur le dépot flask-admin). https://flask-admin.readthedocs.io/en/latest/advanced/#managing-geographical-models

**Comment by camillemonchicourt** [comment]
Pour la géométrie, on pourrait utiliser Leaflet.Filelayer comme dans GeoNature pour pouvoir charger un geojson et utiliser la géométrie d'un objet depuis le fichier uploadé. Comme on fait dans Occtax.

**Comment by lpofredc** [comment]
Oui, bonne idée.
Pour le backoffice, je ne vois pas bien l'intérêt d'une intégration en iframe dans le front. Je propose que le lien Admin envoie tout simplement vers un nouvel onglet avec le backoffice.

**Comment by camillemonchicourt** [comment]
Oui ça peut éviter des problèmes.

**Comment by lpofredc** [comment]
Il est nécessaire de raffraichir la page  (`F5`) pour que le lien `admin` s'affiche. L'affichage auto lorsque l'on est admin serait mieux.

**Comment by lpofredc** [comment]
Travail en cours pour la sélection des listes de taxons TaxHub par liste déroulante.

**Comment by orovellotti** [comment]
Pour préciser : 

- Ajouter un programme, une photo, un texte, un titre, et une liste.
- Editer un  programme existant si il y a de déjà des données
- Supprimer un programme sans données associée

**Comment by HamoudaAmine** [comment]
> Pour préciser :
> 
> * Ajouter un programme, une photo, un texte, un titre, et une liste.
> * Editer un  programme existant si il y a de déjà des données
> * Supprimer un programme sans données associée

Programme:  logo du programme
- titre d u programme
- Sous titre de programme (short_desc)
- Description (long_desc)
- photo du programme
- coordonnées gps du programme (polygone)
- une liste taxonomique

pour créer et gérer une liste taxonomique il faut utiliser taxhub
