### ISSUE TITLE
Creer des pages statiques qui apparaissent dans le menu

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#66]
Il faudrait pouvoir ajouter des pages statiques qui s'ajoute au menu

**Comment by camillemonchicourt** [comment]
Dans GeoNature-atlas, on liste dans la conf les pages statiques : https://github.com/PnEcrins/GeoNature-atlas/blob/master/main/configuration/config.py.sample#L181-L189

Elles s'ajoutent automatiquement dans le menu et sont associés à un template HTML que chacun s'adapte ou se créé : http://biodiversite.ecrins-parcnational.fr/presentation

Exemple sur un autre portail avec plus de pages statiques : http://www.biodiv-paysdelaloire.fr/donnees

**Comment by orovellotti** [comment]
On inclue un model de page HTML qui est liee dans le menu du haut "En Savoir plus" 
L'administrateur du geonature met en forme le fichier HTML pour ses besoin

Il utilise le CSS du site pour mettre en forme sa page.
