### ISSUE TITLE
Avoir plusieurs fonds de carte

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#67]
Possibilité d'afficher le WMS de l'IGN. 
Laisser la possibilité de basculer entre plusieurs fond Ortho et le Scan (cf Biodiv'Ecrins)
![fond](https://user-images.githubusercontent.com/1989428/53796906-5eee4180-3f35-11e9-99f8-61f026d50afc.jpg)

**Comment by camillemonchicourt** [comment]
Un bouton simple qui permet de switcher entre 2 fonds : Carte / Photo
Les URL de ces 2 fonds carto sont 2 paramètres et chacun utilise le fond qu'il souhaite (IGN, OSM, Bing, Mapbox...)

**Comment by patkap** [comment]
![image](https://user-images.githubusercontent.com/11497003/57619443-3f534500-7586-11e9-81cc-5f46f98673b6.png)
@samuelpriou , aurais-tu testé le bouton qui permet "de passer d'un fond topographique à un fond orthophotographique" (point 6)?

**Comment by samuelpriou** [comment]
@patkap Ce bouton est intuitif. Il permet de basculer sur le fond de son choix (topographique ou orthophographique, etc). Ok pour moi.

**Comment by lpofredc** [comment]
Fonds IGN avec clé intégré dans la PR #133.

**Comment by lpofredc** [comment]
Suite des échanges dans l'issue #135

**Comment by camillemonchicourt** [comment]
Le bouton a été intégré uniquement sur la carte d'un programme, mais pas sur la carte de saisie d'une observation. 
A rajouter.

**Comment by camillemonchicourt** [comment]
Bouton disponible sur les différentes cartes.
