### ISSUE TITLE
[NS] Formulaire Observation - Ajouter bouton Carte plein écran

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-citizen#68]
Ajouter le bouton Leaflet permettant de passer le carte de localisation d'une observation en plein écran.

**Comment by patkap** [comment]
Es-tu en train d'évoquer la fonctionnalité du chevron ?

![image](https://user-images.githubusercontent.com/11497003/53812347-97a11180-3f5b-11e9-96a4-9fd6cd75e7d6.png)

**Comment by camillemonchicourt** [comment]
Non je parlais sur le formulaire de saisie d'une observation. 
La carte est toute petite dans le formulaire, ce qui n'est pas un problème, mais ça vaut le coup de pouvoir la passer en plein écran pour faciliter la localisation de l'observation. 
Avec https://github.com/Leaflet/Leaflet.fullscreen

**Comment by lpofredc** [comment]
Tout comme la possibilité d'activer/désactiver la géolocalisation comme évoqué dans ce précédent ticket #48.

**Comment by patkap** [comment]
@camillemonchicourt , @lpofredc , @samuelpriou: Pouvez-vous me confirmer que c'est le plugin que vous souhaitez utiliser, svp ?
http://leaflet.github.io/Leaflet.fullscreen/

**Comment by camillemonchicourt** [comment]
Oui c'est bien ça.

**Comment by samuelpriou** [comment]
Lorsqu'on active le bouton plein écran, cela oblige d'utiliser la touche échap pour valider l'obs. 
Conservons nous cette fonctionnalité ?

**Comment by camillemonchicourt** [comment]
Oui, important de pouvoir passer en plein écran, sinon la carte est toute petite.
Ils peuvent aussi recliquer sur le bouton pour repasser en petite carte.

**Comment by lpofredc** [comment]
Fait
