### ISSUE TITLE
Export pour GeoNature

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#71]
Il faudra prévoir un export pour geoNature validation pour valider les observations

**Comment by camillemonchicourt** [comment]
Il s'agirait d'un trigger optionnel permettant d'alimenter les données de GN-citizen vers la Synthèse de GeoNature. 
Non obligatoire car certains utiliseront GN-citizen sans le brancher à GeoNature.

**Comment by samuelpriou** [comment]
Autre solution préconisée par la société Ascanio :
- Développer un script automatique pour créer une passerelle entre GeoNature-Citizen vers la synthèse de GeoNature. Une routine python s'exécute tous les jours ou toutes les X heures (à définir). Ce type de routine serait plus efficient et plu sécurisé qu'un trigger SQL. A préciser lors des échanges à venir.

**Comment by camillemonchicourt** [comment]
Si la synthèse est alimentée par un trigger, alors un gros travail a été fait par le PNC dans le module Monitoring. 
Voir  https://github.com/PnX-SI/gn_module_monitoring#cr%C3%A9ation-dune-vue-pour-la-synth%C3%A8se
Avec un mécanisme de vue de base que l'on peut compléter par Protocole pour l'adapter selon les champs additionnels.
Détails :  https://github.com/PnX-SI/gn_module_monitoring/issues/14
Et en complément, au niveau de la Synthèse des fonctions ont été intégrées et sont utilisées par Monitoring pour poster des données de Monitoring > Synthèse :  https://github.com/PnX-SI/GeoNature/issues/736

**Comment by lpofredc** [comment]
Merci @camillemonchicourt,

Lors des derniers échanges que nous avons eu avec @samuelpriou, pour les métadonnées, nous proposions d'avoir:
* un cadre d'acquisition GeoNature-citizen (ou par portail Citizen le cas échéant), à générer automatiquement (ou à identifier d'après un paramètre `id_acquisition_framework` en option dans la config?)
* un jeu de données par programme, à générer automatiquement avec des valeurs par défaut.

**Comment by camillemonchicourt** [comment]
Oui ça pourrait être quelque chose comme ça, mais ça ne doit pas être imposé et fixe.
Selon moi il faut uniquement pouvoir définir un id_dataset au niveau de chaque programme de GeoNature-citizen.
Pas besoin de faire référence à un cadre d'acquisition.

Par exemple, si je devais déployer GeoNature-citizen sur notre instance, je me créerai d'abord un CA nommé "Collecte citoyenne" (et non pas "GeoNature-citizen qui est un outil et pas un CA) et ensuite j'y associerai des JDD par programme.

Mais il est fort probable que certains des programmes soient à associer à des JDD dans d'autres CA (dans le CA d'un ABC par exemple à côté de JDD d'experts).

Donc il faut uniquement pouvoir définir un ``id_dataset`` par programme de GeoNature-citizen, et je ne les créerai pas depuis GeoNature-citizen, mais au préalable dans GeoNature.

**Comment by lpofredc** [comment]
Un script optionnel d'intégration automatique des données de GeoNature-citizen dans GeoNature a été développé. Ce script requiert que GeoNature-citizen soit installé dans la même base de données que GeoNature.

cf. https://github.com/PnX-SI/GeoNature-citizen/tree/dev/data/addons/scripts/gnc2gn_synthese

Pour ce faire, un niveau hiérarchique **Projets** a été ajouté. On a donc l'organisation suivante:

- **Projets** > Cadres d'acquisitions
- **Programmes** > Jeux de données
- **Observations** > Occurrence de taxon en synthèse

Les triggers permettent donc la création automatique des **cadres d'acquisition**, **jeux de données** et **occurrences de taxons**.

Ce script intègre la possibilité de renseigner les nomenclatures de la synthèse à partir des formulaires personnalisés, basé sur le réferentiel de nomenclatures. Les `titleMap` permettant de générer ces select sont fournis dans le `README` du script.

**Comment by lpofredc** [comment]
NB. Les données de Citizen ont par défaut le statut de validation `En attente de validation`.

**Comment by camillemonchicourt** [comment]
Merci pour le script et sa documentation.
