### ISSUE TITLE
[NS] Formulaire saisie observation - Saisie date

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-citizen#72]
Ne pas permettre de saisir une date supérieure à la date du jour.

**Comment by lpofredc** [comment]
Le *datepicker* à la saisie d'une date d'observation est instable (testé sur la PR #93). 
1. De base, il propose la date du jour, très bien.
2.  Ensuite, la date est transformée en date agrégée, on passe alors au jour précédent (dans l'exemple, du 11/04/2019 au 10/04/2019). A ce moment là, le champ devient invalide.
3. Enfin, la date enregistrée est la date générée qui correspond à j-1 par rapport à la date saisie.

![Capture d’écran - 2019-04-11 à 21 36 00](https://user-images.githubusercontent.com/22891423/55988051-2f082b80-5ca3-11e9-9cf6-7efb48d15ad7.png)

![Capture d’écran - 2019-04-11 à 21 36 07](https://user-images.githubusercontent.com/22891423/55988064-33344900-5ca3-11e9-96d2-81bcdde2a420.png)

![Capture d’écran - 2019-04-11 à 21 36 26](https://user-images.githubusercontent.com/22891423/55988072-37606680-5ca3-11e9-8ede-70aa9845247d.png)

![Capture d’écran - 2019-04-11 à 21 36 32](https://user-images.githubusercontent.com/22891423/55988075-3b8c8400-5ca3-11e9-8d5c-649acd49d253.png)

**Comment by patkap** [comment]
En effet, il doit y avoir une coquille parce que l'on est pas sensé pouvoir valider le formulaire (bouton actif) si les champs ne sont pas au vert.
Je regarde ça demain.

**Comment by patkap** [comment]
Merci @lpofredc 
- Lorsque l'on compose une chaîne de validateurs sous angular, ils sont tous évalués lors de la validation, même si le 1er est en échec.
- Nous avons désormais des dates UTC pour les obs et les photos, côtés front et back.
