### ISSUE TITLE
[NS] Detail d'une observation 

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#73]
Le click sur les jumelles fait apparaitre le tooltip sur la carte 
![voir une observation](https://user-images.githubusercontent.com/1989428/53797885-66aee580-3f37-11e9-8348-5a132eb3781d.png)

**Comment by lpofredc** [comment]
L'information est redondante avec l'observation dans la liste. Ne pourrais-t-on pas envisager un zoom sur l'observation puis l'affichage du tooltip avec uniquement la photo de l'espèce (remplacée par la photo prise si existante) et le nom de l'espèce?
