### ISSUE TITLE
[NS] Liste des programme sur la Home

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#74]
Revoir l'UX du déroulé des programmes.

![sans titre](https://user-images.githubusercontent.com/1989428/53798162-f5bbfd80-3f37-11e9-8c38-62256b616e11.png)

**Comment by camillemonchicourt** [comment]
Oui je préférerai voir directement tous les programmes, sans avoir à slider. 
Quitte à avoir un paramètre PROGRAM_LIST_SLIDER (true/false) pour ne pas casser ce qui a été fait.

**Comment by lpofredc** [comment]
Pour l'image du programme, (badge origami?), un champ texte `image` est présent dans la table des programmes. permettant d'indiquer le nom du fichier correspondant.

**Comment by orovellotti** [comment]
![Programme responsive](https://user-images.githubusercontent.com/1989428/55780826-23511500-5aa9-11e9-94fb-0913fa441f0b.png)

en mode mobile le fonctionnement est correct

**Comment by camillemonchicourt** [comment]
Oui c'est surtout que le slider n'est pas une solution pertinente.
Il faudrait juste afficher les programmes disponibles sous forme de bloc

**Comment by lpofredc** [comment]
Le slider me parait intéressant pour un affichage mobile et si le programmes sont peu nombreux. 

Ce qui était attendu, c'est un affichage card-deck comme sur l'exemple suivant > https://getbootstrap.com/docs/4.1/components/card/#card-decks

![Sélection_284](https://user-images.githubusercontent.com/22891423/55832753-862cc580-5b16-11e9-99ad-52affdd6324a.png)

**Comment by camillemonchicourt** [comment]
Les sliders c'est pas mal pour un diaporama photo, sinon c'est assez pénible.

**Comment by samuelpriou** [comment]
Effectivement le slider est intéressant pour le mobile mais pour le web l'affichage card-deck est à privilégier.
La solution serait de pouvoir utiliser les card-deck comme des sliders sur le mobile...

**Comment by Naomi-Fischer** [comment]
Bonjour,
Suite à vos dernières demandes, voici la nouvelle disposition des programmes sur la page d'accueil :  
![programs_cards](https://user-images.githubusercontent.com/39299152/56141679-8fe27d00-5f9d-11e9-837d-a7e9d4c476de.JPG)
Le comportement restant le même que le précédent (slider) pour les versions mobile et tablette.
Dans l'attente de votre confirmation, en vous souhaitant une bonne fin de journée !

**Comment by samuelpriou** [comment]
C'est très bien comme cela pour le web. Par contre quel est le comportement des card desks si les programmes sont plus nombreux (>3) ?
Pour le mobile et les tablettes c'est une bonne chose que de conserver les sliders.
Merci !

**Comment by camillemonchicourt** [comment]
Les cards passent à la ligne selon leur nombre

**Comment by samuelpriou** [comment]
C'est tout bon alors !
