### ISSUE TITLE
Rendre configurable le bouton "Participer au programme"

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature-citizen#75]
Permettre aux structures de pouvoir afficher le texte souhaité dans le bouton
![lien_programme](https://user-images.githubusercontent.com/9743288/53887442-9686e780-4022-11e9-936a-18341ddf4fcb.jpg)

**Comment by lpofredc** [comment]
Je propose de le gérer en bdd avec un nom par défaut (dans la config) mais personnalisable dans la table des programmes (champ 'participate_button'?). Je propose également de pouvoir personnaliser le bouton "Ajouter une observation".

**Comment by lpofredc** [comment]
Dans le fichier de conf `app.config.ts`
