### ISSUE TITLE
Les programmes doivent pouvoir être activables et désactivables

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#76]

**Comment by lpofredc** [comment]
Un champ booléen `is_active`en bdd dans la table des programmes permet de choisir le statut d'un programme (est actif ou est désactivé).

**Comment by camillemonchicourt** [comment]
Oui à gérer au niveau de l'API pour ne renvoyer que les actifs.

**Comment by lpofredc** [comment]
Fait dans cette PR #77
