### ISSUE TITLE
Choix des ports

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#78]
Le port 5001 du backend a été remplacé par le port 5002 dans cette PR #77. Le port 5001 étant déjà utilisé par usershubv2.

Les autre ports actuellement utilisés sont 4200 pour le frontend en service (pour le dev) et surtout 4000 pour le service en mode `server side rendering`.

Il serait intéressant que ces ports soient configurables pour éviter d'utiliser des ports déjà utilisés sans modifier le code source.

**Comment by patkap** [comment]
Pour le SSR, le serveur démarre sur le port correspondant à la variable d’environnement `PORT` s'il elle existe sinon le 4000 ... si ça peut faire avancer les choses.
