### ISSUE TITLE
[NS] Rendu mobile

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#79]
Sur petit écran (mobile), quelques retours :
* la barre du haut prend beaucoup de hauteur, je propose réduire sa hauteur sur petit écran? Et/ou de la cacher si l'on descend sur la page.
* le bloc liste/carte simultané sur la page rend la navigation difficile > passer chaque élément à 100% de hauteur? Tout comme l'ensemble des blocs 
* Comme pour sur ce ticket #55, il y a un problème de positionnement de la carte. 
* Si on clique sur un lien comme 'Participer au programme', on ne peut plus revenir en haut de page, ça nous renvoie immédiatement à l'ancre du lien.
![capture d ecran - 2019-03-08 a 00 01 16](https://user-images.githubusercontent.com/22891423/53995428-4fd5e200-4135-11e9-9fc5-3a69e14bfd46.png)

![capture d ecran - 2019-03-08 a 00 00 23](https://user-images.githubusercontent.com/22891423/53995389-346ad700-4135-11e9-8924-219342ed55ab.png)

**Comment by samuelpriou** [comment]
Effectivement le bloc liste/carte simultané sur la page rend la navigation difficile. Il faudrait tester de passer chaque élément à 100% de hauteur comme l'a évoqué @lpofredc  ?

**Comment by samuelpriou** [comment]
Si l'utilisateur décide de stopper la saisie d'une observation, il ne peut pas revenir au menu principal.

**Comment by patkap** [comment]
Il va falloir éclaircir ce dernier point, stp ? ... un click/tap en dehors de la modale / du formulaire d'observation et ça se ferme. Ensuite et depuis le menu "hamburger" toute la navigation est à portée.

**Comment by lpofredc** [comment]
Salut @patkap, il s'agirait simplement d'ajouter l'icone de fermeture du modal dans son header ou plus explicitement, d'ajouter un bouton "annuler" en bas de modal, à côté du bouton de validation de l'observation. A voir le plus ergonomique.

________________________________
De : patkap <notifications@github.com>
Envoyé : samedi 11 mai 2019 12:42:41
À : PnX-SI/GeoNature-citizen
Cc : Frederic Cloitre; Mention
Objet : Re: [PnX-SI/GeoNature-citizen] [NS] Rendu mobile (#79)


Il va falloir éclaircir ce dernier point, stp ? ... un click/tap en dehors de la modale / du formulaire d'observation et ça se ferme. Ensuite et depuis le menu "hamburger" toute la navigation est à portée.

**Comment by camillemonchicourt** [comment]
Le fonctionnement responsive sur mobile a été amélioré depuis, avec un onglet Liste ou Carte pour passer facilement de l'un à l'autre : 

![image](https://github.com/PnX-SI/GeoNature-citizen/assets/4418840/8d9922c0-9fde-420b-b172-4d2e9e1ca404)
