### ISSUE TITLE
[NS] Configuration

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#8]
Il est donc nécessaire de pouvoir configurer la plateforme sur les trois dimensions suivantes:

Login : 
- Logger obligatoire 
- Logger ou non Logger
- Jamais Logger

Programme: 

- Programme une espèces
- Programme moins de 10 espèces
- Programme plus de 10 espèces

Gamification:
- Badges 
- Pas Badges

Est ce que vous pouvez préciser les cas ou vous vous situez?

**Comment by DonovanMaillard** [comment]
Le log obligatoire ou non est il configure pour l'ensemble de linstance, ou est ce que cela se fait programme par programme ?

**Comment by camillemonchicourt** [comment]
Global sur l'instance

**Comment by orovellotti** [comment]
Il faut aussi pouvoir configurer l'url pour "en savoir plus" pour un taxon.

**Comment by lpofredc** [comment]
Cette lien 'en savoir plus' sur un taxon a sauté...

**Comment by lpofredc** [comment]
# Point d'avancement de ce ticket

## Login
- Logger obligatoire > Pas implanté
- Logger ou non Logger > Uniquement côté frontend >`signup: true` dans `frontent/src/conf/app.config.ts`
- Jamais Logger > Uniquement côté frontend >`signup: false` dans `frontent/src/conf/app.config.ts`

## Saisie d'une observation
- Programme une espèces > Oui, mais pas des plus ergonomique, même fonctionnement qu'une liste courte à vignette avec préselection de la seule vignette affichée. Il aurait été préférable d'avoir une image pleine qui prenne toute la largeur du modal.
- Programme à liste courte (par défaut, moins de 7) > vignettes cliquables
- Programme à liste moyenne (par défaut, de 7 jusqu'à 15 espèces ) > liste déroulante avec "microvignette" > Préférer une sélection d'espèce et l'affichage de l'image correspondante en plus grand.
- Programme plus de 10 espèces > autocomplete au comportement semblable à la liste déroulante précédente, même remarque. autocomplétion basée sur "nom_complet", "nom_vern", "nom_vern_eng", "cd_nom" (configurable).

## Gamification

- Badges > Aucune option
- Pas Badges > Aucune option
