### ISSUE TITLE
[NS] Saisie d'une observation: Utiliser TaxHub pour la liste d'espèces d'un programme

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#82]
Actuellement, la liste d'espèce consultée par le frontend la saisie d'une observation est celle générée par le backend de GeoNature citizen, amené à disparaitre au profit de TaxHub. Changer l'url par l'url taxhub pour obtenir les espèces d'une liste.

**Comment by patkap** [comment]
merge with #12 ?

**Comment by lpofredc** [comment]
La liste d'espèce générée par GNCitizen est corrigée dans cette PR #86. 

Se pose la question d'une dépendance forte avec TaxHub (consultation via l'API TaxHub par le front ou d'une dépendance partielle possiblement gérée en bdd et ou les listes sont générées par le backend GeoNature-citizen comme c'est le cas aujourd'hui).

**Comment by camillemonchicourt** [comment]
Oui c'est peut être dommage d'imposer de dépendre de l'API TaxHub.
Mais si on l'utilise beaucoup c'est pratique ?

**Comment by lpofredc** [comment]
Actuellement, GeoNature-citizen reprend à l'identique les tables du schéma `taxonomie` de taxhub et dispose de ses propres routes pour la génération des listes d'espèces. Ceci rend donc facultatif l'installation de TaxHub. 

Mais cela soulève quelques contraintes pour une installation "standalone" :

-  Peupler la table taxref avant de pouvoir créer ses propres listes d'espèces.  Mais cela fonctionne aussi très bien avec une instance de taxhub.
- Gérer manuellement les médias d'illustrations des espèces (sauf si utilisation des scripts de @amandine-sahl avec les api wikimedia ou inpn) et reproduire les redimensionnement des images pour une utilisation dans les programmes.

Si on reprend avec l'utilisation de TaxHub, il faut reprendre certains éléments du frontend car la structure du json des liste d'espèce n'est pas le même.

**Comment by lpofredc** [comment]
Au regard de la bonne intégration d'instances TaxHub distantes (gestion des listes d'espèces et surtout des médias), l'installation du schema `taxonomy` (Copier/Coller de TaxHub) perd de son utilité. Je propose à terme de simplifier le MCD de GeoNature-citizen en supprimant la dépendance au  schéma `taxonomy`.

**Comment by camillemonchicourt** [comment]
Fait dans https://github.com/PnX-SI/GeoNature-citizen/pull/321 et intégré dans la version 1.0.0.
