### ISSUE TITLE
[NS] url des médias enregistrés à la saisie

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#87]
Les médias chargés à la saisie d'une observation sont chargés dans le dossier `medias` de l'installation de GeoNature-citizen.

Le frontend cherche les médias à l'url de l'API.
```typescript
AppConfig.API_ENDPOINT + '/media/' + o.properties.images[0]
```
Or, la gestion des médias (en tout cas à l'heure actuelle), n'est pas assurée par l'API. Leur mise en ligne est à assurée par le serveur web (apache/nginx à configurer pour). Il faut donc plutôt utiliser le paramêtre "URL_APPLICATION" de app.config.ts.

```typescript
AppConfig.URL_APPLICATION + '/media/' + o.properties.images[0]
```

**Comment by patkap** [comment]
Nous avons une route définie à la fin du fichier `backend/gncitizen/core/observations/routes.py`, faut-il la supprimer aussi ?

**Comment by lpofredc** [comment]
Ok, je n'avais pas vue cette nouvelle route.

On peut donc garder la desserte via API, ça offre des perspective de gestion de dimensions (avec Pillow par exemple) et permet d'éviter une configuration supplémentaire du serveur web., En revanche, je ne comprends pas comment est généré l'url de l'image.

Dans mon fichier de config `app.config.ts`, j'ai `API_ENDPOINT":"http://localhost:5002/api"`, or, l'url de l'image de l'appli en service, 
`<img _ngcontent-c4="" src="http://url.com/gncitizen/api/media/obstax_3766_1_20190314_113326.png">`

**Comment by patkap** [comment]
tu aurais un rewrite côté reverse proxy ?

**Comment by lpofredc** [comment]
J'ai réussi en local sans trop comprendre ce qui s'est passé. Je retenterai plus tard.

Ok donc pour rester avec le fonctionnement actuel.
