### ISSUE TITLE
Saisie d'une observation sur la carte

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#89]
Il faut pouvoir passer la carte en plein écran

![Saisie d'une obs plein ecrant](https://user-images.githubusercontent.com/1989428/55783514-e0923b80-5aae-11e9-85e6-7a2e233fe198.png)

**Comment by camillemonchicourt** [comment]
Duplicate https://github.com/PnX-SI/GeoNature-citizen/issues/68
