### ISSUE TITLE
Gestion des mots de passe perdu 

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#90]
Il faut pouvoir récupérer son mot de passe. 
L'utilisateur a un lien j'ai oublier mon mot de passe, il saisie sont adresse mail et reçois un lien pour régénérer le mot de passe.

Cela nécessite d'avoir un serveur SMTP  SendMail par exemple  ou d'utiliser un service tiers SendGrid, MailChimp

**Comment by lpofredc** [comment]
Ou peut-être d'utliser la librairie Python smtplib et une adresse mail existante. Ca évite la configuration lourde d'un serveur sendmail.

```python
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def send_email():
    to_emails= "monmail@domaine.tld"
    message="Hi, this is the email body"
    s = smtplib.SMTP(host='smtp.domain.tld', port=587)
    s.starttls()
    s.login('monmail@domaine.tld','monpass')
    msg = MIMEMultipart()
    msg['From']='monmail@domaine.tld''
    msg['To']='monmail@domaine.tld''
    msg['Subject']="My Subject"
    msg.attach(MIMEText(message, 'plain'))
    s.send_message(msg)
    del msg
    s.quit()

send_email()
```

**Comment by camillemonchicourt** [comment]
Oui Fred

**Comment by orovellotti** [comment]
Il faut un serveur SMTP pour envoyer le mail

**Comment by lpofredc** [comment]
Duplicate of #63

**Comment by camillemonchicourt** [comment]
Pour faire simple autant utiliser un SMTP tiers paramétrable dans la configuration pour éviter de devoir installer un SMTP au niveau de GeoNature-citizen

**Comment by lpofredc** [comment]
Oui @camillemonchicourt. 
Paramètres SMTP à indiquer dans le fichier de config et utiliser stmplib pour envoyer les messages aux demandeurs.
