### ISSUE TITLE
Retirer les dossiers __pycache__ 

### ISSUE THREAD

**Issue by ksamuel** [PnX-SI/GeoNature-citizen#94]
Ils ne sont pas portables et peuvent poser problème si on fait un clone sur une machine différente de celle qui l'a produit. Par ailleurs les fichiers .pyc sont automatiquement regénérés par la VM Python.

```
git rm --cached */**/__pycache__/*
echo "__pycache__" >> .gitignore
```

**Comment by patkap** [comment]
Tous à fait d'accord, et c'est le cas pour le gitignore de la branche dev.

**Comment by lpofredc** [comment]
Corrigé dans ce commit https://github.com/PnX-SI/GeoNature-citizen/commit/e3980593a21b277f3b46baf1e7588a07a908f8f6.
Merci.
