### ISSUE TITLE
[NS] Pas de message d'erreur lors d'un echec d'authentification

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#96]
Tentative d'authentification avec les mauvais identifiant et mot de passe, la console renvoie bien l'erreur 400 mais la fenêtre d'authentification ne renvoie aucun message d'erreur (alert BootStrap). (l'api renvoie `User tartampion doesn't exist`).

**Comment by patkap** [comment]
Donc, on veut une alerte par dessus la modale dans ce cas là ?

**Comment by lpofredc** [comment]
Plutôt dans le `modal-body`, au dessus du formulaire. A moins de faire un composant plus générique à l'ensemble de l'appli. que l'on pourra appeler dans différentes situations, auquel cas un `alert` en overlay pourrait être intéressant.

**Comment by lpofredc** [comment]
PS, je pense qu'il faut revoir la condification des retours d'erreurs dans l'API pour homogénéiser tout ça. 

Aujourd'hui, l'erreur de login ne renvoie que ça ce qui n'est pas vraiment explicite (*mea culpa*)
```json
{
  "message": "User string doesn't exist"
}
```
