### ISSUE TITLE
Carte en mode tactile

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature-citizen#98]
Le scroll sur la carte en mode tactile déclenche automatiquement le PAN ce qui ne permet plus de revenir en haut ou en bas si carte occupe la totalité de l'écran.

Il existe un workaround habituel pour ce genre de problématique, qui est d'imposer le PAN à deux doigts.

https://elmarquis.github.io/Leaflet.GestureHandling/examples/

Je recommande de mettre en place ce comportement.

**Comment by camillemonchicourt** [comment]
Oui quand on est en mobile, c'est une solution intéressante.

**Comment by orovellotti** [comment]
Est ce qu’on valide cette solution?

**Comment by lpofredc** [comment]
Oui, ça me parait intéressant, c'est ce qui est pratiqué avec google-maps.

________________________________
De : Rovellotti <notifications@github.com>
Envoyé : mardi 23 avril 2019 21:12:02
À : PnX-SI/GeoNature-citizen
Cc : Subscribed
Objet : Re: [PnX-SI/GeoNature-citizen] Carte en mode tactile (#98)


Est ce qu’on valide cette solution?

**Comment by samuelpriou** [comment]
Bonjour Olivier,
Oui nous validons ce comportement.
